class UCountry {
  UCountry({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.flag,
    required this.capital,
    required this.continent,
    required this.primaryReligion,
    required this.currency,
    required this.primaryLanguage,
  });

  final String name;
  final String code;
  final String dialCode;
  final String flag;
  final String capital;
  final String continent;
  final String primaryReligion;
  final String currency;
  final String primaryLanguage;

  static List<UCountry> list = <UCountry>[
    UCountry(name: "Andorra", code: "AD", dialCode: "+376", flag: "ad.png", capital: "Andorra la Vella", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Catalan"),
    UCountry(name: "United Arab Emirates", code: "AE", dialCode: "+971", flag: "ae.png", capital: "Abu Dhabi", continent: "Asia", primaryReligion: "Islam", currency: "AED", primaryLanguage: "Arabic"),
    UCountry(name: "Afghanistan", code: "AF", dialCode: "+93", flag: "af.png", capital: "Kabul", continent: "Asia", primaryReligion: "Islam", currency: "AFN", primaryLanguage: "Pashto"),
    UCountry(name: "Antigua and Barbuda", code: "AG", dialCode: "+1-268", flag: "ag.png", capital: "Saint John's", continent: "North America", primaryReligion: "Christianity", currency: "XCD", primaryLanguage: "English"),
    UCountry(name: "Anguilla", code: "AI", dialCode: "+1-264", flag: "ai.png", capital: "The Valley", continent: "North America", primaryReligion: "Christianity", currency: "XCD", primaryLanguage: "English"),
    UCountry(name: "Albania", code: "AL", dialCode: "+355", flag: "al.png", capital: "Tirana", continent: "Europe", primaryReligion: "Islam", currency: "ALL", primaryLanguage: "Albanian"),
    UCountry(name: "Armenia", code: "AM", dialCode: "+374", flag: "am.png", capital: "Yerevan", continent: "Asia", primaryReligion: "Christianity", currency: "AMD", primaryLanguage: "Armenian"),
    UCountry(name: "Angola", code: "AO", dialCode: "+244", flag: "ao.png", capital: "Luanda", continent: "Africa", primaryReligion: "Christianity", currency: "AOA", primaryLanguage: "Portuguese"),
    UCountry(name: "Antarctica", code: "AQ", dialCode: "+672", flag: "aq.png", capital: "None", continent: "Antarctica", primaryReligion: "None", currency: "None", primaryLanguage: "None"),
    UCountry(name: "Argentina", code: "AR", dialCode: "+54", flag: "ar.png", capital: "Buenos Aires", continent: "South America", primaryReligion: "Christianity", currency: "ARS", primaryLanguage: "Spanish"),
    UCountry(name: "American Samoa", code: "AS", dialCode: "+1-684", flag: "as.png", capital: "Pago Pago", continent: "Oceania", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "English"),
    UCountry(name: "Austria", code: "AT", dialCode: "+43", flag: "at.png", capital: "Vienna", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "German"),
    UCountry(name: "Australia", code: "AU", dialCode: "+61", flag: "au.png", capital: "Canberra", continent: "Oceania", primaryReligion: "Christianity", currency: "AUD", primaryLanguage: "English"),
    UCountry(name: "Aruba", code: "AW", dialCode: "+297", flag: "aw.png", capital: "Oranjestad", continent: "North America", primaryReligion: "Christianity", currency: "AWG", primaryLanguage: "Dutch"),
    UCountry(name: "Åland Islands", code: "AX", dialCode: "+358", flag: "ax.png", capital: "Mariehamn", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Swedish"),
    UCountry(name: "Azerbaijan", code: "AZ", dialCode: "+994", flag: "az.png", capital: "Baku", continent: "Asia", primaryReligion: "Islam", currency: "AZN", primaryLanguage: "Azerbaijani"),
    UCountry(name: "Bosnia and Herzegovina", code: "BA", dialCode: "+387", flag: "ba.png", capital: "Sarajevo", continent: "Europe", primaryReligion: "Islam", currency: "BAM", primaryLanguage: "Bosnian"),
    UCountry(name: "Barbados", code: "BB", dialCode: "+1-246", flag: "bb.png", capital: "Bridgetown", continent: "North America", primaryReligion: "Christianity", currency: "BBD", primaryLanguage: "English"),
    UCountry(name: "Bangladesh", code: "BD", dialCode: "+880", flag: "bd.png", capital: "Dhaka", continent: "Asia", primaryReligion: "Islam", currency: "BDT", primaryLanguage: "Bengali"),
    UCountry(name: "Belgium", code: "BE", dialCode: "+32", flag: "be.png", capital: "Brussels", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Dutch"),
    UCountry(name: "Burkina Faso", code: "BF", dialCode: "+226", flag: "bf.png", capital: "Ouagadougou", continent: "Africa", primaryReligion: "Islam", currency: "XOF", primaryLanguage: "French"),
    UCountry(name: "Bulgaria", code: "BG", dialCode: "+359", flag: "bg.png", capital: "Sofia", continent: "Europe", primaryReligion: "Christianity", currency: "BGN", primaryLanguage: "Bulgarian"),
    UCountry(name: "Bahrain", code: "BH", dialCode: "+973", flag: "bh.png", capital: "Manama", continent: "Asia", primaryReligion: "Islam", currency: "BHD", primaryLanguage: "Arabic"),
    UCountry(name: "Burundi", code: "BI", dialCode: "+257", flag: "bi.png", capital: "Gitega", continent: "Africa", primaryReligion: "Christianity", currency: "BIF", primaryLanguage: "Kirundi"),
    UCountry(name: "Benin", code: "BJ", dialCode: "+229", flag: "bj.png", capital: "Porto-Novo", continent: "Africa", primaryReligion: "Christianity", currency: "XOF", primaryLanguage: "French"),
    UCountry(name: "Saint Barthélemy", code: "BL", dialCode: "+590", flag: "bl.png", capital: "Gustavia", continent: "North America", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "Bermuda", code: "BM", dialCode: "+1-441", flag: "bm.png", capital: "Hamilton", continent: "North America", primaryReligion: "Christianity", currency: "BMD", primaryLanguage: "English"),
    UCountry(name: "Brunei", code: "BN", dialCode: "+673", flag: "bn.png", capital: "Bandar Seri Begawan", continent: "Asia", primaryReligion: "Islam", currency: "BND", primaryLanguage: "Malay"),
    UCountry(name: "Bolivia", code: "BO", dialCode: "+591", flag: "bo.png", capital: "Sucre", continent: "South America", primaryReligion: "Christianity", currency: "BOB", primaryLanguage: "Spanish"),
    UCountry(name: "Caribbean Netherlands", code: "BQ", dialCode: "+599", flag: "bq.png", capital: "Kralendijk", continent: "North America", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "Dutch"),
    UCountry(name: "Brazil", code: "BR", dialCode: "+55", flag: "br.png", capital: "Brasília", continent: "South America", primaryReligion: "Christianity", currency: "BRL", primaryLanguage: "Portuguese"),
    UCountry(name: "Bahamas", code: "BS", dialCode: "+1-242", flag: "bs.png", capital: "Nassau", continent: "North America", primaryReligion: "Christianity", currency: "BSD", primaryLanguage: "English"),
    UCountry(name: "Bhutan", code: "BT", dialCode: "+975", flag: "bt.png", capital: "Thimphu", continent: "Asia", primaryReligion: "Buddhism", currency: "BTN", primaryLanguage: "Dzongkha"),
    UCountry(name: "Bouvet Island", code: "BV", dialCode: "+47", flag: "bv.png", capital: "None", continent: "Antarctica", primaryReligion: "None", currency: "NOK", primaryLanguage: "Norwegian"),
    UCountry(name: "Botswana", code: "BW", dialCode: "+267", flag: "bw.png", capital: "Gaborone", continent: "Africa", primaryReligion: "Christianity", currency: "BWP", primaryLanguage: "English"),
    UCountry(name: "Belarus", code: "BY", dialCode: "+375", flag: "by.png", capital: "Minsk", continent: "Europe", primaryReligion: "Christianity", currency: "BYN", primaryLanguage: "Belarusian"),
    UCountry(name: "Belize", code: "BZ", dialCode: "+501", flag: "bz.png", capital: "Belmopan", continent: "North America", primaryReligion: "Christianity", currency: "BZD", primaryLanguage: "English"),
    UCountry(name: "Canada", code: "CA", dialCode: "+1", flag: "ca.png", capital: "Ottawa", continent: "North America", primaryReligion: "Christianity", currency: "CAD", primaryLanguage: "English"),
    UCountry(name: "Cocos (Keeling) Islands", code: "CC", dialCode: "+61", flag: "cc.png", capital: "West Island", continent: "Asia", primaryReligion: "Islam", currency: "AUD", primaryLanguage: "English"),
    UCountry(name: "Democratic Republic of the Congo", code: "CD", dialCode: "+243", flag: "cd.png", capital: "Kinshasa", continent: "Africa", primaryReligion: "Christianity", currency: "CDF", primaryLanguage: "French"),
    UCountry(name: "Central African Republic", code: "CF", dialCode: "+236", flag: "cf.png", capital: "Bangui", continent: "Africa", primaryReligion: "Christianity", currency: "XAF", primaryLanguage: "French"),
    UCountry(name: "Republic of the Congo", code: "CG", dialCode: "+242", flag: "cg.png", capital: "Brazzaville", continent: "Africa", primaryReligion: "Christianity", currency: "XAF", primaryLanguage: "French"),
    UCountry(name: "Switzerland", code: "CH", dialCode: "+41", flag: "ch.png", capital: "Bern", continent: "Europe", primaryReligion: "Christianity", currency: "CHF", primaryLanguage: "German"),
    UCountry(name: "Ivory Coast", code: "CI", dialCode: "+225", flag: "ci.png", capital: "Yamoussoukro", continent: "Africa", primaryReligion: "Islam", currency: "XOF", primaryLanguage: "French"),
    UCountry(name: "Cook Islands", code: "CK", dialCode: "+682", flag: "ck.png", capital: "Avarua", continent: "Oceania", primaryReligion: "Christianity", currency: "NZD", primaryLanguage: "English"),
    UCountry(name: "Chile", code: "CL", dialCode: "+56", flag: "cl.png", capital: "Santiago", continent: "South America", primaryReligion: "Christianity", currency: "CLP", primaryLanguage: "Spanish"),
    UCountry(name: "Cameroon", code: "CM", dialCode: "+237", flag: "cm.png", capital: "Yaoundé", continent: "Africa", primaryReligion: "Christianity", currency: "XAF", primaryLanguage: "French"),
    UCountry(name: "China", code: "CN", dialCode: "+86", flag: "cn.png", capital: "Beijing", continent: "Asia", primaryReligion: "None", currency: "CNY", primaryLanguage: "Mandarin"),
    UCountry(name: "Colombia", code: "CO", dialCode: "+57", flag: "co.png", capital: "Bogotá", continent: "South America", primaryReligion: "Christianity", currency: "COP", primaryLanguage: "Spanish"),
    UCountry(name: "Costa Rica", code: "CR", dialCode: "+506", flag: "cr.png", capital: "San José", continent: "North America", primaryReligion: "Christianity", currency: "CRC", primaryLanguage: "Spanish"),
    UCountry(name: "Cuba", code: "CU", dialCode: "+53", flag: "cu.png", capital: "Havana", continent: "North America", primaryReligion: "Christianity", currency: "CUP", primaryLanguage: "Spanish"),
    UCountry(name: "Cape Verde", code: "CV", dialCode: "+238", flag: "cv.png", capital: "Praia", continent: "Africa", primaryReligion: "Christianity", currency: "CVE", primaryLanguage: "Portuguese"),
    UCountry(name: "Curaçao", code: "CW", dialCode: "+599", flag: "cw.png", capital: "Willemstad", continent: "North America", primaryReligion: "Christianity", currency: "ANG", primaryLanguage: "Dutch"),
    UCountry(name: "Christmas Island", code: "CX", dialCode: "+61", flag: "cx.png", capital: "Flying Fish Cove", continent: "Asia", primaryReligion: "Buddhism", currency: "AUD", primaryLanguage: "English"),
    UCountry(name: "Cyprus", code: "CY", dialCode: "+357", flag: "cy.png", capital: "Nicosia", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Greek"),
    UCountry(name: "Czech Republic", code: "CZ", dialCode: "+420", flag: "cz.png", capital: "Prague", continent: "Europe", primaryReligion: "None", currency: "CZK", primaryLanguage: "Czech"),
    UCountry(name: "Germany", code: "DE", dialCode: "+49", flag: "de.png", capital: "Berlin", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "German"),
    UCountry(name: "Djibouti", code: "DJ", dialCode: "+253", flag: "dj.png", capital: "Djibouti", continent: "Africa", primaryReligion: "Islam", currency: "DJF", primaryLanguage: "French"),
    UCountry(name: "Denmark", code: "DK", dialCode: "+45", flag: "dk.png", capital: "Copenhagen", continent: "Europe", primaryReligion: "Christianity", currency: "DKK", primaryLanguage: "Danish"),
    UCountry(name: "Dominica", code: "DM", dialCode: "+1-767", flag: "dm.png", capital: "Roseau", continent: "North America", primaryReligion: "Christianity", currency: "XCD", primaryLanguage: "English"),
    UCountry(name: "Dominican Republic", code: "DO", dialCode: "+1-809", flag: "do.png", capital: "Santo Domingo", continent: "North America", primaryReligion: "Christianity", currency: "DOP", primaryLanguage: "Spanish"),
    UCountry(name: "Algeria", code: "DZ", dialCode: "+213", flag: "dz.png", capital: "Algiers", continent: "Africa", primaryReligion: "Islam", currency: "DZD", primaryLanguage: "Arabic"),
    UCountry(name: "Ecuador", code: "EC", dialCode: "+593", flag: "ec.png", capital: "Quito", continent: "South America", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "Spanish"),
    UCountry(name: "Estonia", code: "EE", dialCode: "+372", flag: "ee.png", capital: "Tallinn", continent: "Europe", primaryReligion: "None", currency: "EUR", primaryLanguage: "Estonian"),
    UCountry(name: "Egypt", code: "EG", dialCode: "+20", flag: "eg.png", capital: "Cairo", continent: "Africa", primaryReligion: "Islam", currency: "EGP", primaryLanguage: "Arabic"),
    UCountry(name: "Western Sahara", code: "EH", dialCode: "+212", flag: "eh.png", capital: "El Aaiún", continent: "Africa", primaryReligion: "Islam", currency: "MAD", primaryLanguage: "Arabic"),
    UCountry(name: "Eritrea", code: "ER", dialCode: "+291", flag: "er.png", capital: "Asmara", continent: "Africa", primaryReligion: "Christianity", currency: "ERN", primaryLanguage: "Tigrinya"),
    UCountry(name: "Spain", code: "ES", dialCode: "+34", flag: "es.png", capital: "Madrid", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Spanish"),
    UCountry(name: "Ethiopia", code: "ET", dialCode: "+251", flag: "et.png", capital: "Addis Ababa", continent: "Africa", primaryReligion: "Christianity", currency: "ETB", primaryLanguage: "Amharic"),
    UCountry(name: "Finland", code: "FI", dialCode: "+358", flag: "fi.png", capital: "Helsinki", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Finnish"),
    UCountry(name: "Fiji", code: "FJ", dialCode: "+679", flag: "fj.png", capital: "Suva", continent: "Oceania", primaryReligion: "Christianity", currency: "FJD", primaryLanguage: "English"),
    UCountry(name: "Falkland Islands", code: "FK", dialCode: "+500", flag: "fk.png", capital: "Stanley", continent: "South America", primaryReligion: "Christianity", currency: "FKP", primaryLanguage: "English"),
    UCountry(name: "Micronesia", code: "FM", dialCode: "+691", flag: "fm.png", capital: "Palikir", continent: "Oceania", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "English"),
    UCountry(name: "Faroe Islands", code: "FO", dialCode: "+298", flag: "fo.png", capital: "Tórshavn", continent: "Europe", primaryReligion: "Christianity", currency: "DKK", primaryLanguage: "Faroese"),
    UCountry(name: "France", code: "FR", dialCode: "+33", flag: "fr.png", capital: "Paris", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "Gabon", code: "GA", dialCode: "+241", flag: "ga.png", capital: "Libreville", continent: "Africa", primaryReligion: "Christianity", currency: "XAF", primaryLanguage: "French"),
    UCountry(name: "United Kingdom", code: "GB", dialCode: "+44", flag: "gb.png", capital: "London", continent: "Europe", primaryReligion: "Christianity", currency: "GBP", primaryLanguage: "English"),
    UCountry(name: "England", code: "GB-ENG", dialCode: "+44", flag: "gb-eng.png", capital: "London", continent: "Europe", primaryReligion: "Christianity", currency: "GBP", primaryLanguage: "English"),
    UCountry(name: "Northern Ireland", code: "GB-NIR", dialCode: "+44", flag: "gb-nir.png", capital: "Belfast", continent: "Europe", primaryReligion: "Christianity", currency: "GBP", primaryLanguage: "English"),
    UCountry(name: "Scotland", code: "GB-SCT", dialCode: "+44", flag: "gb-sct.png", capital: "Edinburgh", continent: "Europe", primaryReligion: "Christianity", currency: "GBP", primaryLanguage: "English"),
    UCountry(name: "Wales", code: "GB-WLS", dialCode: "+44", flag: "gb-wls.png", capital: "Cardiff", continent: "Europe", primaryReligion: "Christianity", currency: "GBP", primaryLanguage: "English"),
    UCountry(name: "Grenada", code: "GD", dialCode: "+1-473", flag: "gd.png", capital: "St. George's", continent: "North America", primaryReligion: "Christianity", currency: "XCD", primaryLanguage: "English"),
    UCountry(name: "Georgia", code: "GE", dialCode: "+995", flag: "ge.png", capital: "Tbilisi", continent: "Asia", primaryReligion: "Christianity", currency: "GEL", primaryLanguage: "Georgian"),
    UCountry(name: "French Guiana", code: "GF", dialCode: "+594", flag: "gf.png", capital: "Cayenne", continent: "South America", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "Guernsey", code: "GG", dialCode: "+44", flag: "gg.png", capital: "St. Peter Port", continent: "Europe", primaryReligion: "Christianity", currency: "GBP", primaryLanguage: "English"),
    UCountry(name: "Ghana", code: "GH", dialCode: "+233", flag: "gh.png", capital: "Accra", continent: "Africa", primaryReligion: "Christianity", currency: "GHS", primaryLanguage: "English"),
    UCountry(name: "Gibraltar", code: "GI", dialCode: "+350", flag: "gi.png", capital: "Gibraltar", continent: "Europe", primaryReligion: "Christianity", currency: "GIP", primaryLanguage: "English"),
    UCountry(name: "Greenland", code: "GL", dialCode: "+299", flag: "gl.png", capital: "Nuuk", continent: "North America", primaryReligion: "Christianity", currency: "DKK", primaryLanguage: "Greenlandic"),
    UCountry(name: "Gambia", code: "GM", dialCode: "+220", flag: "gm.png", capital: "Banjul", continent: "Africa", primaryReligion: "Islam", currency: "GMD", primaryLanguage: "English"),
    UCountry(name: "Guinea", code: "GN", dialCode: "+224", flag: "gn.png", capital: "Conakry", continent: "Africa", primaryReligion: "Islam", currency: "GNF", primaryLanguage: "French"),
    UCountry(name: "Guadeloupe", code: "GP", dialCode: "+590", flag: "gp.png", capital: "Basse-Terre", continent: "North America", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "Equatorial Guinea", code: "GQ", dialCode: "+240", flag: "gq.png", capital: "Malabo", continent: "Africa", primaryReligion: "Christianity", currency: "XAF", primaryLanguage: "Spanish"),
    UCountry(name: "Greece", code: "GR", dialCode: "+30", flag: "gr.png", capital: "Athens", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Greek"),
    UCountry(name: "South Georgia", code: "GS", dialCode: "+500", flag: "gs.png", capital: "King Edward Point", continent: "Antarctica", primaryReligion: "Christianity", currency: "GBP", primaryLanguage: "English"),
    UCountry(name: "Guatemala", code: "GT", dialCode: "+502", flag: "gt.png", capital: "Guatemala City", continent: "North America", primaryReligion: "Christianity", currency: "GTQ", primaryLanguage: "Spanish"),
    UCountry(name: "Guam", code: "GU", dialCode: "+1-671", flag: "gu.png", capital: "Hagåtña", continent: "Oceania", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "English"),
    UCountry(name: "Guinea-Bissau", code: "GW", dialCode: "+245", flag: "gw.png", capital: "Bissau", continent: "Africa", primaryReligion: "Islam", currency: "XOF", primaryLanguage: "Portuguese"),
    UCountry(name: "Guyana", code: "GY", dialCode: "+592", flag: "gy.png", capital: "Georgetown", continent: "South America", primaryReligion: "Christianity", currency: "GYD", primaryLanguage: "English"),
    UCountry(name: "Hong Kong", code: "HK", dialCode: "+852", flag: "hk.png", capital: "Hong Kong", continent: "Asia", primaryReligion: "Buddhism", currency: "HKD", primaryLanguage: "Chinese"),
    UCountry(name: "Heard Island and McDonald Islands", code: "HM", dialCode: "+672", flag: "hm.png", capital: "None", continent: "Antarctica", primaryReligion: "None", currency: "AUD", primaryLanguage: "English"),
    UCountry(name: "Honduras", code: "HN", dialCode: "+504", flag: "hn.png", capital: "Tegucigalpa", continent: "North America", primaryReligion: "Christianity", currency: "HNL", primaryLanguage: "Spanish"),
    UCountry(name: "Croatia", code: "HR", dialCode: "+385", flag: "hr.png", capital: "Zagreb", continent: "Europe", primaryReligion: "Christianity", currency: "HRK", primaryLanguage: "Croatian"),
    UCountry(name: "Haiti", code: "HT", dialCode: "+509", flag: "ht.png", capital: "Port-au-Prince", continent: "North America", primaryReligion: "Christianity", currency: "HTG", primaryLanguage: "French"),
    UCountry(name: "Hungary", code: "HU", dialCode: "+36", flag: "hu.png", capital: "Budapest", continent: "Europe", primaryReligion: "Christianity", currency: "HUF", primaryLanguage: "Hungarian"),
    UCountry(name: "Indonesia", code: "ID", dialCode: "+62", flag: "id.png", capital: "Jakarta", continent: "Asia", primaryReligion: "Islam", currency: "IDR", primaryLanguage: "Indonesian"),
    UCountry(name: "Ireland", code: "IE", dialCode: "+353", flag: "ie.png", capital: "Dublin", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "English"),
    UCountry(name: "Israel", code: "IL", dialCode: "+972", flag: "il.png", capital: "Jerusalem", continent: "Asia", primaryReligion: "Judaism", currency: "ILS", primaryLanguage: "Hebrew"),
    UCountry(name: "Isle of Man", code: "IM", dialCode: "+44", flag: "im.png", capital: "Douglas", continent: "Europe", primaryReligion: "Christianity", currency: "GBP", primaryLanguage: "English"),
    UCountry(name: "India", code: "IN", dialCode: "+91", flag: "in.png", capital: "New Delhi", continent: "Asia", primaryReligion: "Hinduism", currency: "INR", primaryLanguage: "Hindi"),
    UCountry(name: "British Indian Ocean Territory", code: "IO", dialCode: "+246", flag: "io.png", capital: "Diego Garcia", continent: "Asia", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "English"),
    UCountry(name: "Iraq", code: "IQ", dialCode: "+964", flag: "iq.png", capital: "Baghdad", continent: "Asia", primaryReligion: "Islam", currency: "IQD", primaryLanguage: "Arabic"),
    UCountry(name: "Iran", code: "IR", dialCode: "+98", flag: "ir.png", capital: "Tehran", continent: "Asia", primaryReligion: "Islam", currency: "IRR", primaryLanguage: "Persian"),
    UCountry(name: "Iceland", code: "IS", dialCode: "+354", flag: "is.png", capital: "Reykjavik", continent: "Europe", primaryReligion: "Christianity", currency: "ISK", primaryLanguage: "Icelandic"),
    UCountry(name: "Italy", code: "IT", dialCode: "+39", flag: "it.png", capital: "Rome", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Italian"),
    UCountry(name: "Jersey", code: "JE", dialCode: "+44", flag: "je.png", capital: "Saint Helier", continent: "Europe", primaryReligion: "Christianity", currency: "GBP", primaryLanguage: "English"),
    UCountry(name: "Jamaica", code: "JM", dialCode: "+1-876", flag: "jm.png", capital: "Kingston", continent: "North America", primaryReligion: "Christianity", currency: "JMD", primaryLanguage: "English"),
    UCountry(name: "Jordan", code: "JO", dialCode: "+962", flag: "jo.png", capital: "Amman", continent: "Asia", primaryReligion: "Islam", currency: "JOD", primaryLanguage: "Arabic"),
    UCountry(name: "Japan", code: "JP", dialCode: "+81", flag: "jp.png", capital: "Tokyo", continent: "Asia", primaryReligion: "Shinto", currency: "JPY", primaryLanguage: "Japanese"),
    UCountry(name: "Kenya", code: "KE", dialCode: "+254", flag: "ke.png", capital: "Nairobi", continent: "Africa", primaryReligion: "Christianity", currency: "KES", primaryLanguage: "Swahili"),
    UCountry(name: "Kyrgyzstan", code: "KG", dialCode: "+996", flag: "kg.png", capital: "Bishkek", continent: "Asia", primaryReligion: "Islam", currency: "KGS", primaryLanguage: "Kyrgyz"),
    UCountry(name: "Cambodia", code: "KH", dialCode: "+855", flag: "kh.png", capital: "Phnom Penh", continent: "Asia", primaryReligion: "Buddhism", currency: "KHR", primaryLanguage: "Khmer"),
    UCountry(name: "Kiribati", code: "KI", dialCode: "+686", flag: "ki.png", capital: "Tarawa", continent: "Oceania", primaryReligion: "Christianity", currency: "AUD", primaryLanguage: "English"),
    UCountry(name: "Comoros", code: "KM", dialCode: "+269", flag: "km.png", capital: "Moroni", continent: "Africa", primaryReligion: "Islam", currency: "KMF", primaryLanguage: "Comorian"),
    UCountry(name: "Saint Kitts and Nevis", code: "KN", dialCode: "+1-869", flag: "kn.png", capital: "Basseterre", continent: "North America", primaryReligion: "Christianity", currency: "XCD", primaryLanguage: "English"),
    UCountry(name: "North Korea", code: "KP", dialCode: "+850", flag: "kp.png", capital: "Pyongyang", continent: "Asia", primaryReligion: "None", currency: "KPW", primaryLanguage: "Korean"),
    UCountry(name: "South Korea", code: "KR", dialCode: "+82", flag: "kr.png", capital: "Seoul", continent: "Asia", primaryReligion: "None", currency: "KRW", primaryLanguage: "Korean"),
    UCountry(name: "Kuwait", code: "KW", dialCode: "+965", flag: "kw.png", capital: "Kuwait City", continent: "Asia", primaryReligion: "Islam", currency: "KWD", primaryLanguage: "Arabic"),
    UCountry(name: "Cayman Islands", code: "KY", dialCode: "+1-345", flag: "ky.png", capital: "George Town", continent: "North America", primaryReligion: "Christianity", currency: "KYD", primaryLanguage: "English"),
    UCountry(name: "Kazakhstan", code: "KZ", dialCode: "+7", flag: "kz.png", capital: "Nur-Sultan", continent: "Asia", primaryReligion: "Islam", currency: "KZT", primaryLanguage: "Kazakh"),
    UCountry(name: "Laos", code: "LA", dialCode: "+856", flag: "la.png", capital: "Vientiane", continent: "Asia", primaryReligion: "Buddhism", currency: "LAK", primaryLanguage: "Lao"),
    UCountry(name: "Lebanon", code: "LB", dialCode: "+961", flag: "lb.png", capital: "Beirut", continent: "Asia", primaryReligion: "Islam", currency: "LBP", primaryLanguage: "Arabic"),
    UCountry(name: "Saint Lucia", code: "LC", dialCode: "+1-758", flag: "lc.png", capital: "Castries", continent: "North America", primaryReligion: "Christianity", currency: "XCD", primaryLanguage: "English"),
    UCountry(name: "Liechtenstein", code: "LI", dialCode: "+423", flag: "li.png", capital: "Vaduz", continent: "Europe", primaryReligion: "Christianity", currency: "CHF", primaryLanguage: "German"),
    UCountry(name: "Sri Lanka", code: "LK", dialCode: "+94", flag: "lk.png", capital: "Colombo", continent: "Asia", primaryReligion: "Buddhism", currency: "LKR", primaryLanguage: "Sinhala"),
    UCountry(name: "Liberia", code: "LR", dialCode: "+231", flag: "lr.png", capital: "Monrovia", continent: "Africa", primaryReligion: "Christianity", currency: "LRD", primaryLanguage: "English"),
    UCountry(name: "Lesotho", code: "LS", dialCode: "+266", flag: "ls.png", capital: "Maseru", continent: "Africa", primaryReligion: "Christianity", currency: "LSL", primaryLanguage: "Sesotho"),
    UCountry(name: "Lithuania", code: "LT", dialCode: "+370", flag: "lt.png", capital: "Vilnius", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Lithuanian"),
    UCountry(name: "Luxembourg", code: "LU", dialCode: "+352", flag: "lu.png", capital: "Luxembourg", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Luxembourgish"),
    UCountry(name: "Latvia", code: "LV", dialCode: "+371", flag: "lv.png", capital: "Riga", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Latvian"),
    UCountry(name: "Libya", code: "LY", dialCode: "+218", flag: "ly.png", capital: "Tripoli", continent: "Africa", primaryReligion: "Islam", currency: "LYD", primaryLanguage: "Arabic"),
    UCountry(name: "Morocco", code: "MA", dialCode: "+212", flag: "ma.png", capital: "Rabat", continent: "Africa", primaryReligion: "Islam", currency: "MAD", primaryLanguage: "Arabic"),
    UCountry(name: "Monaco", code: "MC", dialCode: "+377", flag: "mc.png", capital: "Monaco", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "Moldova", code: "MD", dialCode: "+373", flag: "md.png", capital: "Chișinău", continent: "Europe", primaryReligion: "Christianity", currency: "MDL", primaryLanguage: "Romanian"),
    UCountry(name: "Montenegro", code: "ME", dialCode: "+382", flag: "me.png", capital: "Podgorica", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Montenegrin"),
    UCountry(name: "Saint Martin", code: "MF", dialCode: "+590", flag: "mf.png", capital: "Marigot", continent: "North America", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "Madagascar", code: "MG", dialCode: "+261", flag: "mg.png", capital: "Antananarivo", continent: "Africa", primaryReligion: "Christianity", currency: "MGA", primaryLanguage: "Malagasy"),
    UCountry(name: "Marshall Islands", code: "MH", dialCode: "+692", flag: "mh.png", capital: "Majuro", continent: "Oceania", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "Marshallese"),
    UCountry(name: "North Macedonia", code: "MK", dialCode: "+389", flag: "mk.png", capital: "Skopje", continent: "Europe", primaryReligion: "Christianity", currency: "MKD", primaryLanguage: "Macedonian"),
    UCountry(name: "Mali", code: "ML", dialCode: "+223", flag: "ml.png", capital: "Bamako", continent: "Africa", primaryReligion: "Islam", currency: "XOF", primaryLanguage: "French"),
    UCountry(name: "Myanmar", code: "MM", dialCode: "+95", flag: "mm.png", capital: "Naypyidaw", continent: "Asia", primaryReligion: "Buddhism", currency: "MMK", primaryLanguage: "Burmese"),
    UCountry(name: "Mongolia", code: "MN", dialCode: "+976", flag: "mn.png", capital: "Ulaanbaatar", continent: "Asia", primaryReligion: "Buddhism", currency: "MNT", primaryLanguage: "Mongolian"),
    UCountry(name: "Macau", code: "MO", dialCode: "+853", flag: "mo.png", capital: "Macau", continent: "Asia", primaryReligion: "Buddhism", currency: "MOP", primaryLanguage: "Chinese"),
    UCountry(name: "Northern Mariana Islands", code: "MP", dialCode: "+1-670", flag: "mp.png", capital: "Saipan", continent: "Oceania", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "English"),
    UCountry(name: "Martinique", code: "MQ", dialCode: "+596", flag: "mq.png", capital: "Fort-de-France", continent: "North America", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "Mauritania", code: "MR", dialCode: "+222", flag: "mr.png", capital: "Nouakchott", continent: "Africa", primaryReligion: "Islam", currency: "MRU", primaryLanguage: "Arabic"),
    UCountry(name: "Montserrat", code: "MS", dialCode: "+1-664", flag: "ms.png", capital: "Plymouth", continent: "North America", primaryReligion: "Christianity", currency: "XCD", primaryLanguage: "English"),
    UCountry(name: "Malta", code: "MT", dialCode: "+356", flag: "mt.png", capital: "Valletta", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Maltese"),
    UCountry(name: "Mauritius", code: "MU", dialCode: "+230", flag: "mu.png", capital: "Port Louis", continent: "Africa", primaryReligion: "Hinduism", currency: "MUR", primaryLanguage: "English"),
    UCountry(name: "Maldives", code: "MV", dialCode: "+960", flag: "mv.png", capital: "Malé", continent: "Asia", primaryReligion: "Islam", currency: "MVR", primaryLanguage: "Dhivehi"),
    UCountry(name: "Malawi", code: "MW", dialCode: "+265", flag: "mw.png", capital: "Lilongwe", continent: "Africa", primaryReligion: "Christianity", currency: "MWK", primaryLanguage: "English"),
    UCountry(name: "Mexico", code: "MX", dialCode: "+52", flag: "mx.png", capital: "Mexico City", continent: "North America", primaryReligion: "Christianity", currency: "MXN", primaryLanguage: "Spanish"),
    UCountry(name: "Malaysia", code: "MY", dialCode: "+60", flag: "my.png", capital: "Kuala Lumpur", continent: "Asia", primaryReligion: "Islam", currency: "MYR", primaryLanguage: "Malay"),
    UCountry(name: "Mozambique", code: "MZ", dialCode: "+258", flag: "mz.png", capital: "Maputo", continent: "Africa", primaryReligion: "Christianity", currency: "MZN", primaryLanguage: "Portuguese"),
    UCountry(name: "Namibia", code: "NA", dialCode: "+264", flag: "na.png", capital: "Windhoek", continent: "Africa", primaryReligion: "Christianity", currency: "NAD", primaryLanguage: "English"),
    UCountry(name: "New Caledonia", code: "NC", dialCode: "+687", flag: "nc.png", capital: "Nouméa", continent: "Oceania", primaryReligion: "Christianity", currency: "XPF", primaryLanguage: "French"),
    UCountry(name: "Niger", code: "NE", dialCode: "+227", flag: "ne.png", capital: "Niamey", continent: "Africa", primaryReligion: "Islam", currency: "XOF", primaryLanguage: "French"),
    UCountry(name: "Norfolk Island", code: "NF", dialCode: "+672", flag: "nf.png", capital: "Kingston", continent: "Oceania", primaryReligion: "Christianity", currency: "AUD", primaryLanguage: "English"),
    UCountry(name: "Nigeria", code: "NG", dialCode: "+234", flag: "ng.png", capital: "Abuja", continent: "Africa", primaryReligion: "Islam", currency: "NGN", primaryLanguage: "English"),
    UCountry(name: "Nicaragua", code: "NI", dialCode: "+505", flag: "ni.png", capital: "Managua", continent: "North America", primaryReligion: "Christianity", currency: "NIO", primaryLanguage: "Spanish"),
    UCountry(name: "Netherlands", code: "NL", dialCode: "+31", flag: "nl.png", capital: "Amsterdam", continent: "Europe", primaryReligion: "None", currency: "EUR", primaryLanguage: "Dutch"),
    UCountry(name: "Norway", code: "NO", dialCode: "+47", flag: "no.png", capital: "Oslo", continent: "Europe", primaryReligion: "Christianity", currency: "NOK", primaryLanguage: "Norwegian"),
    UCountry(name: "Nepal", code: "NP", dialCode: "+977", flag: "np.png", capital: "Kathmandu", continent: "Asia", primaryReligion: "Hinduism", currency: "NPR", primaryLanguage: "Nepali"),
    UCountry(name: "Nauru", code: "NR", dialCode: "+674", flag: "nr.png", capital: "Yaren", continent: "Oceania", primaryReligion: "Christianity", currency: "AUD", primaryLanguage: "English"),
    UCountry(name: "Niue", code: "NU", dialCode: "+683", flag: "nu.png", capital: "Alofi", continent: "Oceania", primaryReligion: "Christianity", currency: "NZD", primaryLanguage: "English"),
    UCountry(name: "New Zealand", code: "NZ", dialCode: "+64", flag: "nz.png", capital: "Wellington", continent: "Oceania", primaryReligion: "Christianity", currency: "NZD", primaryLanguage: "English"),
    UCountry(name: "Oman", code: "OM", dialCode: "+968", flag: "om.png", capital: "Muscat", continent: "Asia", primaryReligion: "Islam", currency: "OMR", primaryLanguage: "Arabic"),
    UCountry(name: "Panama", code: "PA", dialCode: "+507", flag: "pa.png", capital: "Panama City", continent: "North America", primaryReligion: "Christianity", currency: "PAB", primaryLanguage: "Spanish"),
    UCountry(name: "Peru", code: "PE", dialCode: "+51", flag: "pe.png", capital: "Lima", continent: "South America", primaryReligion: "Christianity", currency: "PEN", primaryLanguage: "Spanish"),
    UCountry(name: "French Polynesia", code: "PF", dialCode: "+689", flag: "pf.png", capital: "Papeete", continent: "Oceania", primaryReligion: "Christianity", currency: "XPF", primaryLanguage: "French"),
    UCountry(name: "Papua New Guinea", code: "PG", dialCode: "+675", flag: "pg.png", capital: "Port Moresby", continent: "Oceania", primaryReligion: "Christianity", currency: "PGK", primaryLanguage: "English"),
    UCountry(name: "Philippines", code: "PH", dialCode: "+63", flag: "ph.png", capital: "Manila", continent: "Asia", primaryReligion: "Christianity", currency: "PHP", primaryLanguage: "Tagalog"),
    UCountry(name: "Pakistan", code: "PK", dialCode: "+92", flag: "pk.png", capital: "Islamabad", continent: "Asia", primaryReligion: "Islam", currency: "PKR", primaryLanguage: "Urdu"),
    UCountry(name: "Poland", code: "PL", dialCode: "+48", flag: "pl.png", capital: "Warsaw", continent: "Europe", primaryReligion: "Christianity", currency: "PLN", primaryLanguage: "Polish"),
    UCountry(name: "Saint Pierre and Miquelon", code: "PM", dialCode: "+508", flag: "pm.png", capital: "Saint-Pierre", continent: "North America", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "Pitcairn Islands", code: "PN", dialCode: "+64", flag: "pn.png", capital: "Adamstown", continent: "Oceania", primaryReligion: "Christianity", currency: "NZD", primaryLanguage: "English"),
    UCountry(name: "Puerto Rico", code: "PR", dialCode: "+1-787", flag: "pr.png", capital: "San Juan", continent: "North America", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "Spanish"),
    UCountry(name: "Palestine", code: "PS", dialCode: "+970", flag: "ps.png", capital: "Ramallah", continent: "Asia", primaryReligion: "Islam", currency: "ILS", primaryLanguage: "Arabic"),
    UCountry(name: "Portugal", code: "PT", dialCode: "+351", flag: "pt.png", capital: "Lisbon", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Portuguese"),
    UCountry(name: "Palau", code: "PW", dialCode: "+680", flag: "pw.png", capital: "Ngerulmud", continent: "Oceania", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "Palauan"),
    UCountry(name: "Paraguay", code: "PY", dialCode: "+595", flag: "py.png", capital: "Asunción", continent: "South America", primaryReligion: "Christianity", currency: "PYG", primaryLanguage: "Spanish"),
    UCountry(name: "Qatar", code: "QA", dialCode: "+974", flag: "qa.png", capital: "Doha", continent: "Asia", primaryReligion: "Islam", currency: "QAR", primaryLanguage: "Arabic"),
    UCountry(name: "Réunion", code: "RE", dialCode: "+262", flag: "re.png", capital: "Saint-Denis", continent: "Africa", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "Romania", code: "RO", dialCode: "+40", flag: "ro.png", capital: "Bucharest", continent: "Europe", primaryReligion: "Christianity", currency: "RON", primaryLanguage: "Romanian"),
    UCountry(name: "Serbia", code: "RS", dialCode: "+381", flag: "rs.png", capital: "Belgrade", continent: "Europe", primaryReligion: "Christianity", currency: "RSD", primaryLanguage: "Serbian"),
    UCountry(name: "Russia", code: "RU", dialCode: "+7", flag: "ru.png", capital: "Moscow", continent: "Europe", primaryReligion: "Christianity", currency: "RUB", primaryLanguage: "Russian"),
    UCountry(name: "Rwanda", code: "RW", dialCode: "+250", flag: "rw.png", capital: "Kigali", continent: "Africa", primaryReligion: "Christianity", currency: "RWF", primaryLanguage: "Kinyarwanda"),
    UCountry(name: "Saudi Arabia", code: "SA", dialCode: "+966", flag: "sa.png", capital: "Riyadh", continent: "Asia", primaryReligion: "Islam", currency: "SAR", primaryLanguage: "Arabic"),
    UCountry(name: "Solomon Islands", code: "SB", dialCode: "+677", flag: "sb.png", capital: "Honiara", continent: "Oceania", primaryReligion: "Christianity", currency: "SBD", primaryLanguage: "English"),
    UCountry(name: "Seychelles", code: "SC", dialCode: "+248", flag: "sc.png", capital: "Victoria", continent: "Africa", primaryReligion: "Christianity", currency: "SCR", primaryLanguage: "English"),
    UCountry(name: "Sudan", code: "SD", dialCode: "+249", flag: "sd.png", capital: "Khartoum", continent: "Africa", primaryReligion: "Islam", currency: "SDG", primaryLanguage: "Arabic"),
    UCountry(name: "Sweden", code: "SE", dialCode: "+46", flag: "se.png", capital: "Stockholm", continent: "Europe", primaryReligion: "Christianity", currency: "SEK", primaryLanguage: "Swedish"),
    UCountry(name: "Singapore", code: "SG", dialCode: "+65", flag: "sg.png", capital: "Singapore", continent: "Asia", primaryReligion: "Buddhism", currency: "SGD", primaryLanguage: "English"),
    UCountry(name: "Saint Helena", code: "SH", dialCode: "+290", flag: "sh.png", capital: "Jamestown", continent: "Africa", primaryReligion: "Christianity", currency: "SHP", primaryLanguage: "English"),
    UCountry(name: "Slovenia", code: "SI", dialCode: "+386", flag: "si.png", capital: "Ljubljana", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Slovenian"),
    UCountry(name: "Svalbard and Jan Mayen", code: "SJ", dialCode: "+47", flag: "sj.png", capital: "Longyearbyen", continent: "Europe", primaryReligion: "Christianity", currency: "NOK", primaryLanguage: "Norwegian"),
    UCountry(name: "Slovakia", code: "SK", dialCode: "+421", flag: "sk.png", capital: "Bratislava", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Slovak"),
    UCountry(name: "Sierra Leone", code: "SL", dialCode: "+232", flag: "sl.png", capital: "Freetown", continent: "Africa", primaryReligion: "Islam", currency: "SLL", primaryLanguage: "English"),
    UCountry(name: "San Marino", code: "SM", dialCode: "+378", flag: "sm.png", capital: "San Marino", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Italian"),
    UCountry(name: "Senegal", code: "SN", dialCode: "+221", flag: "sn.png", capital: "Dakar", continent: "Africa", primaryReligion: "Islam", currency: "XOF", primaryLanguage: "French"),
    UCountry(name: "Somalia", code: "SO", dialCode: "+252", flag: "so.png", capital: "Mogadishu", continent: "Africa", primaryReligion: "Islam", currency: "SOS", primaryLanguage: "Somali"),
    UCountry(name: "Suriname", code: "SR", dialCode: "+597", flag: "sr.png", capital: "Paramaribo", continent: "South America", primaryReligion: "Christianity", currency: "SRD", primaryLanguage: "Dutch"),
    UCountry(name: "South Sudan", code: "SS", dialCode: "+211", flag: "ss.png", capital: "Juba", continent: "Africa", primaryReligion: "Christianity", currency: "SSP", primaryLanguage: "English"),
    UCountry(name: "São Tomé and Príncipe", code: "ST", dialCode: "+239", flag: "st.png", capital: "São Tomé", continent: "Africa", primaryReligion: "Christianity", currency: "STN", primaryLanguage: "Portuguese"),
    UCountry(name: "El Salvador", code: "SV", dialCode: "+503", flag: "sv.png", capital: "San Salvador", continent: "North America", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "Spanish"),
    UCountry(name: "Sint Maarten", code: "SX", dialCode: "+1-721", flag: "sx.png", capital: "Philipsburg", continent: "North America", primaryReligion: "Christianity", currency: "ANG", primaryLanguage: "Dutch"),
    UCountry(name: "Syria", code: "SY", dialCode: "+963", flag: "sy.png", capital: "Damascus", continent: "Asia", primaryReligion: "Islam", currency: "SYP", primaryLanguage: "Arabic"),
    UCountry(name: "Eswatini", code: "SZ", dialCode: "+268", flag: "sz.png", capital: "Mbabane", continent: "Africa", primaryReligion: "Christianity", currency: "SZL", primaryLanguage: "Swazi"),
    UCountry(name: "Turks and Caicos Islands", code: "TC", dialCode: "+1-649", flag: "tc.png", capital: "Cockburn Town", continent: "North America", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "English"),
    UCountry(name: "Chad", code: "TD", dialCode: "+235", flag: "td.png", capital: "N'Djamena", continent: "Africa", primaryReligion: "Islam", currency: "XAF", primaryLanguage: "French"),
    UCountry(name: "French Southern Territories", code: "TF", dialCode: "+262", flag: "tf.png", capital: "Port-aux-Français", continent: "Antarctica", primaryReligion: "None", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "Togo", code: "TG", dialCode: "+228", flag: "tg.png", capital: "Lomé", continent: "Africa", primaryReligion: "Christianity", currency: "XOF", primaryLanguage: "French"),
    UCountry(name: "Thailand", code: "TH", dialCode: "+66", flag: "th.png", capital: "Bangkok", continent: "Asia", primaryReligion: "Buddhism", currency: "THB", primaryLanguage: "Thai"),
    UCountry(name: "Tajikistan", code: "TJ", dialCode: "+992", flag: "tj.png", capital: "Dushanbe", continent: "Asia", primaryReligion: "Islam", currency: "TJS", primaryLanguage: "Tajik"),
    UCountry(name: "Tokelau", code: "TK", dialCode: "+690", flag: "tk.png", capital: "Nukunonu", continent: "Oceania", primaryReligion: "Christianity", currency: "NZD", primaryLanguage: "Tokelauan"),
    UCountry(name: "Timor-Leste", code: "TL", dialCode: "+670", flag: "tl.png", capital: "Dili", continent: "Asia", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "Tetum"),
    UCountry(name: "Turkmenistan", code: "TM", dialCode: "+993", flag: "tm.png", capital: "Ashgabat", continent: "Asia", primaryReligion: "Islam", currency: "TMT", primaryLanguage: "Turkmen"),
    UCountry(name: "Tunisia", code: "TN", dialCode: "+216", flag: "tn.png", capital: "Tunis", continent: "Africa", primaryReligion: "Islam", currency: "TND", primaryLanguage: "Arabic"),
    UCountry(name: "Tonga", code: "TO", dialCode: "+676", flag: "to.png", capital: "Nuku'alofa", continent: "Oceania", primaryReligion: "Christianity", currency: "TOP", primaryLanguage: "Tongan"),
    UCountry(name: "Turkey", code: "TR", dialCode: "+90", flag: "tr.png", capital: "Ankara", continent: "Asia", primaryReligion: "Islam", currency: "TRY", primaryLanguage: "Turkish"),
    UCountry(name: "Trinidad and Tobago", code: "TT", dialCode: "+1-868", flag: "tt.png", capital: "Port of Spain", continent: "North America", primaryReligion: "Christianity", currency: "TTD", primaryLanguage: "English"),
    UCountry(name: "Tuvalu", code: "TV", dialCode: "+688", flag: "tv.png", capital: "Funafuti", continent: "Oceania", primaryReligion: "Christianity", currency: "AUD", primaryLanguage: "Tuvaluan"),
    UCountry(name: "Taiwan", code: "TW", dialCode: "+886", flag: "tw.png", capital: "Taipei", continent: "Asia", primaryReligion: "Buddhism", currency: "TWD", primaryLanguage: "Mandarin"),
    UCountry(name: "Tanzania", code: "TZ", dialCode: "+255", flag: "tz.png", capital: "Dodoma", continent: "Africa", primaryReligion: "Christianity", currency: "TZS", primaryLanguage: "Swahili"),
    UCountry(name: "Ukraine", code: "UA", dialCode: "+380", flag: "ua.png", capital: "Kyiv", continent: "Europe", primaryReligion: "Christianity", currency: "UAH", primaryLanguage: "Ukrainian"),
    UCountry(name: "Uganda", code: "UG", dialCode: "+256", flag: "ug.png", capital: "Kampala", continent: "Africa", primaryReligion: "Christianity", currency: "UGX", primaryLanguage: "English"),
    UCountry(name: "United States Minor Outlying Islands", code: "UM", dialCode: "+1", flag: "um.png", capital: "None", continent: "Oceania", primaryReligion: "None", currency: "USD", primaryLanguage: "English"),
    UCountry(name: "United States", code: "US", dialCode: "+1", flag: "us.png", capital: "Washington, D.C.", continent: "North America", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "English"),
    UCountry(name: "Uruguay", code: "UY", dialCode: "+598", flag: "uy.png", capital: "Montevideo", continent: "South America", primaryReligion: "Christianity", currency: "UYU", primaryLanguage: "Spanish"),
    UCountry(name: "Uzbekistan", code: "UZ", dialCode: "+998", flag: "uz.png", capital: "Tashkent", continent: "Asia", primaryReligion: "Islam", currency: "UZS", primaryLanguage: "Uzbek"),
    UCountry(name: "Vatican City", code: "VA", dialCode: "+39", flag: "va.png", capital: "Vatican City", continent: "Europe", primaryReligion: "Christianity", currency: "EUR", primaryLanguage: "Italian"),
    UCountry(name: "Saint Vincent and the Grenadines", code: "VC", dialCode: "+1-784", flag: "vc.png", capital: "Kingstown", continent: "North America", primaryReligion: "Christianity", currency: "XCD", primaryLanguage: "English"),
    UCountry(name: "Venezuela", code: "VE", dialCode: "+58", flag: "ve.png", capital: "Caracas", continent: "South America", primaryReligion: "Christianity", currency: "VES", primaryLanguage: "Spanish"),
    UCountry(name: "British Virgin Islands", code: "VG", dialCode: "+1-284", flag: "vg.png", capital: "Road Town", continent: "North America", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "English"),
    UCountry(name: "U.S. Virgin Islands", code: "VI", dialCode: "+1-340", flag: "vi.png", capital: "Charlotte Amalie", continent: "North America", primaryReligion: "Christianity", currency: "USD", primaryLanguage: "English"),
    UCountry(name: "Vietnam", code: "VN", dialCode: "+84", flag: "vn.png", capital: "Hanoi", continent: "Asia", primaryReligion: "None", currency: "VND", primaryLanguage: "Vietnamese"),
    UCountry(name: "Vanuatu", code: "VU", dialCode: "+678", flag: "vu.png", capital: "Port Vila", continent: "Oceania", primaryReligion: "Christianity", currency: "VUV", primaryLanguage: "Bislama"),
    UCountry(name: "Wallis and Futuna", code: "WF", dialCode: "+681", flag: "wf.png", capital: "Mata-Utu", continent: "Oceania", primaryReligion: "Christianity", currency: "XPF", primaryLanguage: "French"),
    UCountry(name: "Samoa", code: "WS", dialCode: "+685", flag: "ws.png", capital: "Apia", continent: "Oceania", primaryReligion: "Christianity", currency: "WST", primaryLanguage: "Samoan"),
    UCountry(name: "Yemen", code: "YE", dialCode: "+967", flag: "ye.png", capital: "Sanaa", continent: "Asia", primaryReligion: "Islam", currency: "YER", primaryLanguage: "Arabic"),
    UCountry(name: "Mayotte", code: "YT", dialCode: "+262", flag: "yt.png", capital: "Mamoudzou", continent: "Africa", primaryReligion: "Islam", currency: "EUR", primaryLanguage: "French"),
    UCountry(name: "South Africa", code: "ZA", dialCode: "+27", flag: "za.png", capital: "Pretoria", continent: "Africa", primaryReligion: "Christianity", currency: "ZAR", primaryLanguage: "English"),
    UCountry(name: "Zambia", code: "ZM", dialCode: "+260", flag: "zm.png", capital: "Lusaka", continent: "Africa", primaryReligion: "Christianity", currency: "ZMW", primaryLanguage: "English"),
    UCountry(name: "Zimbabwe", code: "ZW", dialCode: "+263", flag: "zw.png", capital: "Harare", continent: "Africa", primaryReligion: "Christianity", currency: "ZWL", primaryLanguage: "English"),
  ];
}
