import "package:u/utilities.dart";

class UBusinessCategory {
  final String code;
  final String nameEn;
  final String nameFa;

  const UBusinessCategory({required this.code, required this.nameEn, required this.nameFa});

  String localizedName() {
    if (UApp.locale() == "fa") return nameFa;
    return nameEn;
  }
}

abstract class BusinessCategories {
  static List<UBusinessCategory> get categories => <UBusinessCategory>[
    const UBusinessCategory(code: "93990008", nameEn: "Foreign Nationals & Sponsorship Office", nameFa: "دفتر کفالت و اتباع خارجی"),
    const UBusinessCategory(code: "07420000", nameEn: "Veterinary Services - Other", nameFa: "خدمات دامپزشکی سایر کسب"),
    const UBusinessCategory(code: "07420001", nameEn: "Veterinary Services", nameFa: "خدمات دامپزشکی"),
    const UBusinessCategory(code: "07630000", nameEn: "Agricultural & Livestock Cooperative - Other", nameFa: "تعاونی کشاورزی و دامداری سایر کسب"),
    const UBusinessCategory(code: "07630001", nameEn: "Livestock Farming", nameFa: "دامداری"),
    const UBusinessCategory(code: "07630002", nameEn: "Agriculture & Horticulture", nameFa: "کشاورزی و باغداری"),
    const UBusinessCategory(code: "07630003", nameEn: "Poultry Farming", nameFa: "مرغداری"),
    const UBusinessCategory(code: "07630004", nameEn: "Beekeeping", nameFa: "پرورش زنبور عسل"),
    const UBusinessCategory(code: "07630005", nameEn: "Fish Farming & Aquaculture", nameFa: "پرورش ماهی و آبزی پروری"),
    const UBusinessCategory(code: "07630006", nameEn: "Mushroom Cultivation", nameFa: "پرورش و تولید قارچ"),
    const UBusinessCategory(code: "07800000", nameEn: "Agricultural & Gardening Services - Other", nameFa: "خدمات کشاورزی و باغبانی سایر کسب"),
    const UBusinessCategory(code: "07800001", nameEn: "Lawn/Turf", nameFa: "چمن"),
    const UBusinessCategory(code: "15200000", nameEn: "Housing Cooperative - Other", nameFa: "تعاونی مسکن سایر کسب"),
    const UBusinessCategory(code: "15200001", nameEn: "Housing Cooperative", nameFa: "تعاونی مسکن"),
    const UBusinessCategory(code: "15200002", nameEn: "Construction & Mass Housing Companies", nameFa: "شرکتهای ساختمانی و انبوه سازی"),
    const UBusinessCategory(code: "17110000", nameEn: "Building Installations - Other", nameFa: "تاسیسات ساختمان سایر کسب"),
    const UBusinessCategory(code: "17110001", nameEn: "Building Installations (Plumbing, Cooling, Heating)", nameFa: "تاسیسات ساختمان(لوله کشی،سرمایشی،گرمایشی)"),
    const UBusinessCategory(code: "17110002", nameEn: "Drain Cleaning & Leak Detection", nameFa: "لوله بازکنی و تشخیص ترکیدگی لوله"),
    const UBusinessCategory(code: "17110003", nameEn: "Septic Tank Emptying", nameFa: "تخلیه چاه"),
    const UBusinessCategory(code: "17110004", nameEn: "HVAC Systems", nameFa: "سیستم های حرارتی، برودتی و تهویه مطبوع"),
    const UBusinessCategory(code: "17110005", nameEn: "Cooler Duct Making", nameFa: "کانال سازی کولر"),
    const UBusinessCategory(code: "17310000", nameEn: "Building Electrical Services - Other", nameFa: "خدمات برق ساختمان سایر کسب"),
    const UBusinessCategory(code: "17310001", nameEn: "Electric Motor, Winding & Generator", nameFa: "الکتروموتور،سیم پیچ و ژنراتور"),
    const UBusinessCategory(code: "17310002", nameEn: "Wiring", nameFa: "سیم کشی"),
    const UBusinessCategory(code: "17310005", nameEn: "Building Electrical Installations", nameFa: "تاسیسات برقی ساختمان"),
    const UBusinessCategory(code: "17400000", nameEn: "Masonry, Architecture, Stonecutting, Carpet & Paint - Other", nameFa: "بنایی، معماری، سنگبری، موکت و پارکت و رنگ ساختمان سایر کسب"),
    const UBusinessCategory(code: "17400001", nameEn: "Masonry & Architecture", nameFa: "بنایی و معماری"),
    const UBusinessCategory(code: "17400002", nameEn: "Gazebo Manufacturing & Installation", nameFa: "تولید و نصب آلاچیق"),
    const UBusinessCategory(code: "17400003", nameEn: "Cement Worker & Mosaic Maker", nameFa: "سیمانکار و موزاییک ساز"),
    const UBusinessCategory(code: "17400004", nameEn: "House Painter", nameFa: "نقاش ساختمان"),
    const UBusinessCategory(code: "17400005", nameEn: "Cement & Cement Products Store", nameFa: "فروشگاه سیمان و مصنوعات سیمانی"),
    const UBusinessCategory(code: "17400006", nameEn: "Brick & Plaster Manufacturing", nameFa: "فخاران تولید آجر و گچ"),
    const UBusinessCategory(code: "17400007", nameEn: "Building Facade Work", nameFa: "نماسازی ساختمان"),
    const UBusinessCategory(code: "17400008", nameEn: "Tile & Ceramic", nameFa: "کاشی و سرامیک"),
    const UBusinessCategory(code: "17400009", nameEn: "Rebar & Frame Work", nameFa: "آرماتور و اسکلت بندی،آهن کشی ساختمان"),
    const UBusinessCategory(code: "17400010", nameEn: "Stone Cutter & Carver", nameFa: "سنگ بر و سنگ تراش"),
    const UBusinessCategory(code: "17400011", nameEn: "Steel Structure Building", nameFa: "سوله سازی"),
    const UBusinessCategory(code: "17500000", nameEn: "Carpentry & Woodwork - Other", nameFa: "نجاری و کارهای چوبی سایر کسب"),
    const UBusinessCategory(code: "17500001", nameEn: "Carpentry & Joinery", nameFa: "نجاری و درودگری"),
    const UBusinessCategory(code: "17500002", nameEn: "Khatam, Inlay & Wood Products", nameFa: "خاتم کاری، منبت کاری و مصنوعات چوبی"),
    const UBusinessCategory(code: "17610000", nameEn: "Roofing Services - Other", nameFa: "شیروانی سازی و خدمات پوشش سقف و بامها سایر کسب"),
    const UBusinessCategory(code: "17710000", nameEn: "Concrete Services - Other", nameFa: "خدمات بتن سایر کسب"),
    const UBusinessCategory(code: "17990000", nameEn: "Other Construction Services", nameFa: "سایر خدمات ساختمانی سایر کسب"),
    const UBusinessCategory(code: "17990001", nameEn: "Scaffolding & Metal Fittings", nameFa: "داربست و اتصالات فلزی"),
    const UBusinessCategory(code: "17990002", nameEn: "Pipes & Building Fittings", nameFa: "لوله و اتصالات ساختمانی"),
    const UBusinessCategory(code: "17990003", nameEn: "Construction Materials", nameFa: "مصالح ساختمانی"),
    const UBusinessCategory(code: "17990005", nameEn: "Elevator & Electric Lift", nameFa: "آسانسور و بالابر برقی"),
    const UBusinessCategory(code: "27410000", nameEn: "Printing & Publishing Services - Other", nameFa: "خدمات چاپ و انتشار متفرقه سایر کسب"),
    const UBusinessCategory(code: "27410001", nameEn: "Printing Houses", nameFa: "چاپ خانه داران"),
    const UBusinessCategory(code: "27410002", nameEn: "Publishing Services", nameFa: "خدمات نشر"),
    const UBusinessCategory(code: "27410003", nameEn: "Typing & Translation Services", nameFa: "خدمات تایپ و ترجمه"),
    const UBusinessCategory(code: "27910000", nameEn: "Typesetting & Lithography - Other", nameFa: "خدمات حروفچینی و لیتوگرافی سایر کسب"),
    const UBusinessCategory(code: "28420000", nameEn: "Cleaning, Polishing & Floor Sanding - Other", nameFa: "خدمات نظافت، جلا و کفسابی سایر کسب"),
    const UBusinessCategory(code: "40110000", nameEn: "Rail Lines - Other", nameFa: "خطوط ریلی سایر کسب"),
    const UBusinessCategory(code: "41110000", nameEn: "Urban & Suburban Transport - Other", nameFa: "حمل و نقل درون و حومه شهر سایر کسب"),
    const UBusinessCategory(code: "41120000", nameEn: "Road", nameFa: "راه"),
    const UBusinessCategory(code: "41190000", nameEn: "Ambulance Services - Other", nameFa: "خدمات آمبولانس سایر کسب"),
    const UBusinessCategory(code: "41210000", nameEn: "Taxi & Car Rental - Other", nameFa: "تاکسیرانی و کرایه اتومبیل سایر کسب"),
    const UBusinessCategory(code: "41310000", nameEn: "Bus Lines - Other", nameFa: "خطوط اتوبوس سایر کسب"),
    const UBusinessCategory(code: "41310001", nameEn: "Intercity Bus Terminal", nameFa: "پایانه اتوبوسی بین شهری"),
    const UBusinessCategory(code: "42140000", nameEn: "Urban & Non-urban Freight - Other", nameFa: "خدمات باربری شهری و غیرشهری سایر کسب"),
    const UBusinessCategory(code: "42150000", nameEn: "Postal & Courier Services - Other", nameFa: "خدمات پستی و پیک سایر کسب"),
    const UBusinessCategory(code: "42250000", nameEn: "Public Warehouse & Cold Storage", nameFa: "انبار عمومی و ذخیره محصولات کشاورزی، سردخانه"),
    const UBusinessCategory(code: "42250001", nameEn: "Cold Storage Services", nameFa: "خدمات سردخانه"),
    const UBusinessCategory(code: "44110000", nameEn: "Shipping Lines & Maritime Transport - Other", nameFa: "خطوط کشتیرانی و حمل و نقل دریایی سایر کسب"),
    const UBusinessCategory(code: "44570000", nameEn: "Boat, Jet Ski & Marine Recreation - Other", nameFa: "خدمات قایق، جت اسکی و تفریحات دریایی سایر کسب"),
    const UBusinessCategory(code: "44680000", nameEn: "Marine Services - Other", nameFa: "خدمات دریایی سایر کسب"),
    const UBusinessCategory(code: "45110000", nameEn: "Airlines & Air Transport - Other", nameFa: "خطوط هواپیمایی و حمل و نقل هوایی سایر کسب"),
    const UBusinessCategory(code: "45820000", nameEn: "Airport", nameFa: "فرودگاه"),
    const UBusinessCategory(code: "47220000", nameEn: "Travel Agency, Tourism & Tour Services - Other", nameFa: "آژانس مسافرتی، خدمات گردشگری و تور سایر کسب"),
    const UBusinessCategory(code: "47840000", nameEn: "Road Tolls - Other", nameFa: "عوارض راه سایر کسب"),
    const UBusinessCategory(code: "47890000", nameEn: "Transport Services [Other]", nameFa: "خدمات حمل و نقل [سایر موارد] سایر کسب"),
    const UBusinessCategory(code: "48120000", nameEn: "Other", nameFa: "سایر کسب"),
    const UBusinessCategory(code: "48120001", nameEn: "Mobile Phone & Accessories", nameFa: "تلفن همراه و تجهیزات جانبی"),
    const UBusinessCategory(code: "48120002", nameEn: "Telephone & Telecom Devices & Equipment", nameFa: "تلفن و دستگاههای مخابراتی وتجهیزات ارتباطی"),
    const UBusinessCategory(code: "48140000", nameEn: "Local & Long-distance Telecom Office", nameFa: "دفتر خدمات مخابراتی محلی و راه"),
    const UBusinessCategory(code: "48160000", nameEn: "Network Services", nameFa: "خدمات شبکه"),
    const UBusinessCategory(code: "48160001", nameEn: "Computer Network Services", nameFa: "خدمات شبکه های کامپيوتری"),
    const UBusinessCategory(code: "48160002", nameEn: "Internet Service Provider", nameFa: "ارائه دهنده خدمات اینترنت"),
    const UBusinessCategory(code: "48210000", nameEn: "Telegraph Services - Other", nameFa: "خدمات تلگراف سایر کسب"),
    const UBusinessCategory(code: "48290000", nameEn: "Electronic Funds Transfer Center - Other", nameFa: "مرکز حواله الکترونیکی وجوه سایر کسب"),
    const UBusinessCategory(code: "48990000", nameEn: "Cable & Pay TV Services - Other", nameFa: "خدمات تلویزیونهای کابلی و پولی سایر کسب"),
    const UBusinessCategory(code: "49000000", nameEn: "Utility Companies (Water, Electricity, Gas) - Other", nameFa: "شرکتهای خدماتی (آب، برق، گاز) سایر کسب"),
    const UBusinessCategory(code: "49000001", nameEn: "Electricity Office & Bills", nameFa: "اداره برق و قبوض آن"),
    const UBusinessCategory(code: "49000002", nameEn: "Gas Office & Bills", nameFa: "اداره گاز و قبوض آن"),
    const UBusinessCategory(code: "49000003", nameEn: "Water & Sewage Office & Bills", nameFa: "اداره آب و فاضلاب و قبوض آن"),
    const UBusinessCategory(code: "50440000", nameEn: "Office, Printing & Photo Supplies - Other", nameFa: "لوازم اداری، چاپی و عکاسی سایر کسب"),
    const UBusinessCategory(code: "50450000", nameEn: "Computer & Peripherals - Other", nameFa: "کامپیوتر و لوازم جانبی سایر کسب"),
    const UBusinessCategory(code: "50460000", nameEn: "Business Machines [Other]", nameFa: "ماشینهای تجاری [ سایر موارد] سایر کسب"),
    const UBusinessCategory(code: "50460001", nameEn: "Audio-Visual Educational Aids", nameFa: "وسایل آموزشی و کمک آموزشی سمعی و بصری"),
    const UBusinessCategory(code: "50460002", nameEn: "Mannequin Manufacturing & Sales", nameFa: "تولید و فروش مانکن"),
    const UBusinessCategory(code: "50470000", nameEn: "Medical, Dental & Hospital Equipment - Other", nameFa: "تجهیزات و لوازم پزشکی، دندانپزشکی و بیمارستانی سایر کسب"),
    const UBusinessCategory(code: "50470001", nameEn: "Medical, Hospital & Laboratory Equipment", nameFa: "تجهیزات و لوازم پزشکی، بیمارستانی و آزمایشگاهی"),
    const UBusinessCategory(code: "50470002", nameEn: "Dental Equipment & Supplies", nameFa: "تجهیزات و لوازم دندانپزشکی"),
    const UBusinessCategory(code: "50510000", nameEn: "Metal Products Sales Centers - Other", nameFa: "دفاتر و مراکز فروش محصولات فلزی سایر کسب"),
    const UBusinessCategory(code: "50510001", nameEn: "Iron, Steel & Other Metals Sellers", nameFa: "فروشندگان آهن، فولاد و سایر فلزات"),
    const UBusinessCategory(code: "50510002", nameEn: "Metal & Non-metal Scrap", nameFa: "ضایعات فلزی و غیرفلزی"),
    const UBusinessCategory(code: "50510003", nameEn: "Machining & Metalwork", nameFa: "تراشکاری و فلزکاری"),
    const UBusinessCategory(code: "50510004", nameEn: "Metal Enameling & Painting", nameFa: "لعاب کاری و رنگ کاری فلزات"),
    const UBusinessCategory(code: "50510005", nameEn: "Ironmongers", nameFa: "آهن سازان"),
    const UBusinessCategory(code: "50510006", nameEn: "Metal Smelting, Casting & Molding", nameFa: "ذوب فلزات،ریخته گری و قالب سازی"),
    const UBusinessCategory(code: "50510007", nameEn: "Aluminum & Rolled Products", nameFa: "آلومینیوم و مصنوعات نوردی آن"),
    const UBusinessCategory(code: "50510008", nameEn: "Copper & Copper Products", nameFa: "مس و مصنوعات مسی"),
    const UBusinessCategory(code: "50510009", nameEn: "Metal Pressing", nameFa: "پرسکاری فلزات"),
    const UBusinessCategory(code: "50510010", nameEn: "Electroplaters", nameFa: "آبکاران"),
    const UBusinessCategory(code: "50510011", nameEn: "Construction Steel - Rebar, Angle & Sheet", nameFa: "آهن آلات ساختمانی میلگرد، نبشی و ورق"),
    const UBusinessCategory(code: "50650000", nameEn: "Electrical Parts & Equipment - Other", nameFa: "قطعات و تجهیزات الکتریکی سایر کسب"),
    const UBusinessCategory(code: "50650001", nameEn: "Wholesale Electronic Equipment & Parts", nameFa: "فروشندگان عمده تجهیزات و قطعات الکترونیکی"),
    const UBusinessCategory(code: "50650002", nameEn: "Panel Makers & Industrial Electrical Firms", nameFa: "تابلوسازان و موسسات برق صنعتی"),
    const UBusinessCategory(code: "50650003", nameEn: "Electrical Appliances & Electronic Boards Manufacturer", nameFa: "تولید کننده لوازم برقی و بردهای الکترونیکی"),
    const UBusinessCategory(code: "50720000", nameEn: "Tools & Equipment - Other", nameFa: "ابزار و تجهیزات سایر کسب"),
    const UBusinessCategory(code: "50720001", nameEn: "Wholesale Tools & Equipment", nameFa: "عمده فروشان ابزار و تجهیزات"),
    const UBusinessCategory(code: "50740000", nameEn: "Pipe Equipment", nameFa: "تجهیزات لوله"),
    const UBusinessCategory(code: "50850000", nameEn: "Industrial Consumables [Other]", nameFa: "موارد مصرفی صنعتی [سایر موارد] سایر کسب"),
    const UBusinessCategory(code: "50940000", nameEn: "Precious Stones, Metals, Watches & Jewelry - Other", nameFa: "سنگها و فلزات گرانبها ساعت و جواهرات سایر کسب"),
    const UBusinessCategory(code: "50990000", nameEn: "Durable Goods [Other]", nameFa: "کالاهای ماندگار [سایر موارد] سایر کسب"),
    const UBusinessCategory(code: "51110000", nameEn: "Stationery, Office Supplies, Printer Paper & Writing Goods", nameFa: "لوازم التحریر، ملزومات دفتری، کاغذ پرینتر و نوشت"),
    const UBusinessCategory(code: "51220000", nameEn: "Pharmaceuticals & Prescription Drugs", nameFa: "دارو، داروهای نسخه"),
    const UBusinessCategory(code: "51310000", nameEn: "Fabric, Wardrobe, Yarn & Other Dry Goods - Other", nameFa: "پارچه، کمد و نخ و سایر کالاهای خشک سایر کسب"),
    const UBusinessCategory(code: "51370000", nameEn: "Women's, Men's & Children's Uniforms", nameFa: "یونفرمهای زنانه، مردانه و بچه"),
    const UBusinessCategory(code: "51390000", nameEn: "Commercial Footwear - Other", nameFa: "کفشهای تجاری سایر کسب"),
    const UBusinessCategory(code: "51690000", nameEn: "Chemicals [Other]", nameFa: "مواد شیمیایی (سایر موارد) سایر کسب"),
    const UBusinessCategory(code: "51690001", nameEn: "Chemical & Organic Materials", nameFa: "مواد شیمیایی و آلی"),
    const UBusinessCategory(code: "51690002", nameEn: "Plastic & Nylon Materials & Products", nameFa: "مواد، مصنوعات پلاستیکی و نایلون"),
    const UBusinessCategory(code: "51690003", nameEn: "Industrial Gases", nameFa: "گازهای صنعتی"),
    const UBusinessCategory(code: "51720000", nameEn: "Crude Oil & Petroleum Products - Other", nameFa: "نفت خام و محصولات نفتی سایر کسب"),
    const UBusinessCategory(code: "51920000", nameEn: "Books, Newspapers & Publications - Other", nameFa: "کتاب، روزنامه و نشریه سایر کسب"),
    const UBusinessCategory(code: "51920001", nameEn: "Wholesale Books, Newspapers & Magazines", nameFa: "توزیع عمده کتاب،روزنامه، مجله و گاهنامه"),
    const UBusinessCategory(code: "51920002", nameEn: "Library", nameFa: "کتابخانه"),
    const UBusinessCategory(code: "51930000", nameEn: "Flowers", nameFa: "گل"),
    const UBusinessCategory(code: "51980000", nameEn: "Paint, Varnish & Painting Consumables - Other", nameFa: "رنگ، جلا و مواد مصرفی نقاشی سایر کسب"),
    const UBusinessCategory(code: "51990000", nameEn: "Other Non-durable Goods", nameFa: "سایر کالاهای غیرماندگار سایر کسب"),
    const UBusinessCategory(code: "52000000", nameEn: "Interior Decoration Supply Stores - Other", nameFa: "فروشگاههای تامین محصولات تزییات داخلی سایر کسب"),
    const UBusinessCategory(code: "52000001", nameEn: "Hood, Sink & Cabinet Store", nameFa: "هود و سینک و کابینت فروشی"),
    const UBusinessCategory(code: "52000002", nameEn: "Building Sanitary Ware", nameFa: "لوازم و کالای بهداشتی ساختمان"),
    const UBusinessCategory(code: "52110000", nameEn: "Lumber & Construction Materials Stores - Other", nameFa: "فروشگاههای الوار و مصالح ساختمانی سایر کسب"),
    const UBusinessCategory(code: "52310000", nameEn: "Glass, Paint & Wallpaper Stores - Other", nameFa: "فروشگاههای شیشه، رنگ و کاغذ دیواری سایر کسب"),
    const UBusinessCategory(code: "52310001", nameEn: "Wallpaper & Interior Decoration", nameFa: "کاغذدیواری و تزیینات داخلی ساختمان"),
    const UBusinessCategory(code: "52310002", nameEn: "Glass Cutting & Mirror Sales", nameFa: "شیشه بری و فروشندگی شیشه و آیینه"),
    const UBusinessCategory(code: "52510000", nameEn: "Tool Shops - Other", nameFa: "ابزار فروشیها سایر کسب"),
    const UBusinessCategory(code: "52510001", nameEn: "Tool Sellers", nameFa: "ابزار فروشان"),
    const UBusinessCategory(code: "52510002", nameEn: "Screw & Bolt Sellers", nameFa: "پیچ و مهره فروشان"),
    const UBusinessCategory(code: "52510003", nameEn: "Lock, Hinge & Hardware Store", nameFa: "فروشگاه قفل، لولا و یراق آلات"),
    const UBusinessCategory(code: "52510004", nameEn: "Locksmith", nameFa: "قفل و کلید سازی"),
    const UBusinessCategory(code: "52610000", nameEn: "Gardening & Greenhouse Supply Stores", nameFa: "فروشگاههای لوازم باغبانی و گلخانه"),
    const UBusinessCategory(code: "52610001", nameEn: "Agricultural & Gardening Materials", nameFa: "مواد اولیه و لوازم کشاورزی و باغبانی"),
    const UBusinessCategory(code: "52610002", nameEn: "Fertilizer, Pesticide & Agricultural Chemicals", nameFa: "کود، سم و داروهای شیمیایی محصولات کشاورزی"),
    const UBusinessCategory(code: "52610003", nameEn: "Irrigation & Water Supply Equipment", nameFa: "لوازم آبیاری و آبرسانی کشاورزی و صنعتی"),
    const UBusinessCategory(code: "52710000", nameEn: "Home Sellers", nameFa: "فروشندگان خانه"),
    const UBusinessCategory(code: "53000000", nameEn: "Wholesalers - Other", nameFa: "عمده فروشیها سایر کسب"),
    const UBusinessCategory(code: "53000001", nameEn: "Wholesale Fruit & Vegetable Sellers", nameFa: "بار فروشان عمده فروشی میوه و تره بار"),
    const UBusinessCategory(code: "53000002", nameEn: "Food Wholesaler - Rice", nameFa: "بنکدار مواد غذایی عمده فروش برنج"),
    const UBusinessCategory(code: "53000003", nameEn: "Food Wholesaler - Tea", nameFa: "بنکدار مواد غذایی عمده فروش چای"),
    const UBusinessCategory(code: "53000004", nameEn: "Food Wholesaler - Edible Oils", nameFa: "بنکدار مواد غذایی عمده فروش روغنهای خوراکی"),
    const UBusinessCategory(code: "53000005", nameEn: "Food Wholesaler - General", nameFa: "بنکدار مواد غذایی عمده فروش کلی"),
    const UBusinessCategory(code: "53000006", nameEn: "Fabric Wholesaler", nameFa: "بنکدار و طاقه فروش پارچه"),
    const UBusinessCategory(code: "53000007", nameEn: "Wholesale Shoemaking Supplies", nameFa: "عمده فروشی لوازم کفاشی"),
    const UBusinessCategory(code: "53000008", nameEn: "Wholesale Detergents & Cleaners", nameFa: "عمده فروش مواد شوینده و پاک کننده"),
    const UBusinessCategory(code: "53090000", nameEn: "Duty-Free Stores - Other", nameFa: "فروشگاههای محصولات معاف از مالیات سایر کسب"),
    const UBusinessCategory(code: "53100000", nameEn: "Auctions - Other", nameFa: "حراجیها سایر کسب"),
    const UBusinessCategory(code: "53110000", nameEn: "Chain Stores", nameFa: "فروشگاههای زنجیره"),
    const UBusinessCategory(code: "53110001", nameEn: "Refah Chain Store", nameFa: "فروشگاه زنجیره ای رفاه"),
    const UBusinessCategory(code: "53110002", nameEn: "Shahrvand Chain Store", nameFa: "فروشگاه زنجیره ای شهروند"),
    const UBusinessCategory(code: "53110003", nameEn: "Etka Chain Store", nameFa: "فروشگاه زنجیره ای اتکا"),
    const UBusinessCategory(code: "50210000", nameEn: "Office & Commercial Furniture - Other", nameFa: "مبلمان اداری و تجاری سایر کسب"),
    const UBusinessCategory(code: "57120000", nameEn: "Furniture, Decor & Home Equipment - Other", nameFa: "مبلمان، تزئینات، تجهیزات خانگی سایر کسب"),
    const UBusinessCategory(code: "57130000", nameEn: "Floor Covering Stores - Other", nameFa: "فروشگاههای کفپوش سایر کسب"),
    const UBusinessCategory(code: "57130001", nameEn: "Carpet, Kilim, Moquette & Tableau Rug Store", nameFa: "فروشگاه فرش، گلیم و موکت و تابلو فرش"),
    const UBusinessCategory(code: "57140000", nameEn: "Curtains, Blinds & Upholstery Fabric - Other", nameFa: "پرده، کرکره و پارچه مبلی سایر کسب"),
    const UBusinessCategory(code: "57140001", nameEn: "Curtain Sewing, Installation & Repair", nameFa: "دوخت نصب و تعمیر انواع پرده"),
    const UBusinessCategory(code: "57140002", nameEn: "Bedspreads & Curtain Decorations", nameFa: "رومبلی،روتختی و تزیینات پرده ای"),
    const UBusinessCategory(code: "57180000", nameEn: "Fireplaces, Hearths & Accessories - Other", nameFa: "شومینه، آتشدان و لوازم جانبی آنها سایر کسب"),
    const UBusinessCategory(code: "57190000", nameEn: "Special & Misc Home Decor - Other", nameFa: "لوازم و تزئینات خانگی خاص و متفرقه سایر کسب"),
    const UBusinessCategory(code: "57190001", nameEn: "Chandelier & Lampshade Sellers", nameFa: "فروشندگان لوستر و آباژور"),
    const UBusinessCategory(code: "57190002", nameEn: "Mirror & Picture Frame Sellers", nameFa: "فروشندگان آیینه و قاب عکس"),
    const UBusinessCategory(code: "57190003", nameEn: "Pottery & Ceramic Goods Sellers", nameFa: "فروشندگان اجناس سفالی و سرامیکی"),
    const UBusinessCategory(code: "57190004", nameEn: "Chandelier & Mirror-Candlestick", nameFa: "لوستر و آیینه شمعدان"),
    const UBusinessCategory(code: "57190005", nameEn: "Packaging & Disposable Containers", nameFa: "لوازم بسته بندی و ظروف یکبار مصرف"),
    const UBusinessCategory(code: "57220000", nameEn: "Home Appliance Store - Other", nameFa: "فروشگاه دستگاههای خانگی سایر کسب"),
    const UBusinessCategory(code: "57220001", nameEn: "Kitchen Utensils & Cookware", nameFa: "لوازم و ظروف آشپزخانه"),
    const UBusinessCategory(code: "57220002", nameEn: "Home Appliance Store", nameFa: "فروشگاه لوازم خانگی"),
    const UBusinessCategory(code: "57320000", nameEn: "Electronics Stores - Other", nameFa: "فروشگاههای لوازم الکترونیکی سایر کسب"),
    const UBusinessCategory(code: "57320001", nameEn: "Audio & Video Equipment Store", nameFa: "فروشگاه لوازم صوتی و تصویری"),
    const UBusinessCategory(code: "57320002", nameEn: "Audio & Video Equipment Dealership", nameFa: "نمایندگی لوازم صوتی و تصویری"),
    const UBusinessCategory(code: "57330000", nameEn: "Musical Instrument Stores (Instruments & Sheet Music) - Other", nameFa: "فروشگاههای لوازم موسیقی (ادوات و نت) سایر کسب"),
    const UBusinessCategory(code: "57340000", nameEn: "Software Stores", nameFa: "فروشگاههای نرم"),
    const UBusinessCategory(code: "57350000", nameEn: "Media Products Store - Other", nameFa: "فروشگاه محصولات رسانه ای سایر کسب"),
    const UBusinessCategory(code: "58110000", nameEn: "Catering - Other", nameFa: "تهیه غذا سایر کسب"),
    const UBusinessCategory(code: "58120000", nameEn: "Eateries & Restaurants - Other", nameFa: "غذافروشی ها و رستورانها سایر کسب"),
    const UBusinessCategory(code: "58120001", nameEn: "Restaurant, Chelokababi & Dining Hall", nameFa: "رستوران، چلوکبابی و سالن غذاخوری"),
    const UBusinessCategory(code: "58120002", nameEn: "Head & Trotter (Kalleh Pacheh) Sellers", nameFa: "طباخان و فروشندگان کله، پاچه و سیرابی"),
    const UBusinessCategory(code: "58120003", nameEn: "Liver, Heart & Kidney", nameFa: "جگر، دل و قلوه"),
    const UBusinessCategory(code: "58120004", nameEn: "Traditional Restaurant (Sofreh Khaneh)", nameFa: "سفره خانه"),
    const UBusinessCategory(code: "58120005", nameEn: "Kababi, Halim & Ash", nameFa: "کبابی، حلیم و آش"),
    const UBusinessCategory(code: "58120006", nameEn: "Banquet Halls", nameFa: "تالار های پذیرایی"),
    const UBusinessCategory(code: "58120007", nameEn: "Tea House & Coffee House", nameFa: "چای خانه و قهوه خانه"),
    const UBusinessCategory(code: "58120008", nameEn: "Coffee Shop & Cafeteria", nameFa: "کافی شاپ و کافه تریا"),
    const UBusinessCategory(code: "58140000", nameEn: "Fast Food Restaurants - Other", nameFa: "رستورانهای فست فود سایر کسب"),
    const UBusinessCategory(code: "58140001", nameEn: "Ice Cream Shop", nameFa: "بستنی فروشی"),
    const UBusinessCategory(code: "58140002", nameEn: "Fast Food Restaurants", nameFa: "رستورانهای غذای آماده"),
    const UBusinessCategory(code: "58150000", nameEn: "Digital Goods - Books, Films, Music & Multimedia - Other", nameFa: "کالاهای دیجیتال کتاب، فیلم، موسیقی و چند -رسانه ای سایر کسب"),
    const UBusinessCategory(code: "58160000", nameEn: "Digital Goods - Digital Games - Other", nameFa: "کالاهای دیجیتال - بازیهای دیجیتال سایر کسب"),
    const UBusinessCategory(code: "58170000", nameEn: "Digital Goods - Applications (Non-game) - Other", nameFa: "کالاهای دیجیتال نرم افزارهای کاربردی (به -غیر از بازی) سایر کسب"),
    const UBusinessCategory(code: "58180000", nameEn: "Digital Goods - Large-scale Digital Sales - Other", nameFa: "کالاهای دیجیتال فروش کالای دیجیتال در مقیاس بزرگ سایر کسب"),
    const UBusinessCategory(code: "59120000", nameEn: "Pharmacy", nameFa: "داروخانه"),
    const UBusinessCategory(code: "59120001", nameEn: "Pharmacy", nameFa: "داروخانه"),
    const UBusinessCategory(code: "59120002", nameEn: "Drug Production & Distribution Services", nameFa: "خدمات تولید و پخش دارو"),
    const UBusinessCategory(code: "59310000", nameEn: "Second-hand Stores (Consignment) - Other", nameFa: "فروشگاههای دسته دوم فروشی (سمساری و امانت فروشی) سایر کسب"),
    const UBusinessCategory(code: "59320000", nameEn: "Antique Shop - Sale, Repair & Restoration - Other", nameFa: "عتیقه فروشی فروش، تعمیر و بازسازی سایر کسب"),
    const UBusinessCategory(code: "59330000", nameEn: "Pawn Shops - Other", nameFa: "فروشگاههای رهنی سایر کسب"),
    const UBusinessCategory(code: "59350000", nameEn: "Auto Salvage Yards - Other", nameFa: "انبارهای اوراق خودرو سایر کسب"),
    const UBusinessCategory(code: "59370000", nameEn: "Antique Replication - Other", nameFa: "همانندسازی عتیقه جات سایر کسب"),
    const UBusinessCategory(code: "59400000", nameEn: "Bicycle Stores - Sales & Service - Other", nameFa: "فروشگاههای دوچرخه- فروش و خدمات سایر کسب"),
    const UBusinessCategory(code: "59410000", nameEn: "Sporting Goods Store - Other", nameFa: "فروشگاه کالای ورزشی سایر کسب"),
    const UBusinessCategory(code: "59410001", nameEn: "Sporting Goods & Equipment", nameFa: "لوازم و کالای ورزشی"),
    const UBusinessCategory(code: "59410002", nameEn: "Hunting & Fishing Supplies", nameFa: "لوازم صید و شکار"),
    const UBusinessCategory(code: "59420000", nameEn: "Bookstores - Other", nameFa: "کتاب فروشیها سایر کسب"),
    const UBusinessCategory(code: "59430000", nameEn: "Stationery & Office Equipment Store - Other", nameFa: "فروشگاه لوازم التحریر و تجهیزات اداری سایر کسب"),
    const UBusinessCategory(code: "59440000", nameEn: "Jewelry, Watches & Silver Stores - Other", nameFa: "فروشگاههای جواهرآلات، ساعت مچی، ساعت، نقره سایر کسب"),
    const UBusinessCategory(code: "59440001", nameEn: "Watch Shop", nameFa: "ساعت فروشی"),
    const UBusinessCategory(code: "59440002", nameEn: "Silverware Shop", nameFa: "نقره فروشی"),
    const UBusinessCategory(code: "59440003", nameEn: "Gold & Jewelry Design & Manufacture", nameFa: "طراحی وساخت طلا و جواهر"),
    const UBusinessCategory(code: "59440004", nameEn: "Gold, Jewelry & Precious Stones Sales", nameFa: "فروش طلا، جواهر و سنگهای قیمتی"),
    const UBusinessCategory(code: "59440005", nameEn: "Gold Coin Retail", nameFa: "خرده فروشی سکه طلا"),
    const UBusinessCategory(code: "59450000", nameEn: "Toy, Game & Hobby Stores - Other", nameFa: "فروشگاههای اسباب بازی، بازی و سرگرمی سایر کسب"),
    const UBusinessCategory(code: "59460000", nameEn: "Camera & Photography Equipment - Other", nameFa: "دوربین و تجهیزات عکاسی و فیلمبرداری سایر کسب"),
    const UBusinessCategory(code: "59470000", nameEn: "Gifts, Cards & Costume Jewelry - Other", nameFa: "کادویی، کارت و بدلیجات سایر کسب"),
    const UBusinessCategory(code: "59470001", nameEn: "Card, Envelope, Box & Paper Products Manufacturing", nameFa: "تولید کارت، پاکت، جعبه و محصولات کاغذی و مقوایی"),
    const UBusinessCategory(code: "59480000", nameEn: "Luggage & Leather Goods - Other", nameFa: "چمدان و کالای چرمی سایر کسب"),
    const UBusinessCategory(code: "59490000", nameEn: "Sewing, Embroidery & Fabric Supplies - Other", nameFa: "لوازم خیاطی، سوزن دوزی و پارچه سایر کسب"),
    const UBusinessCategory(code: "59490001", nameEn: "Embroidery & Needlework", nameFa: "گل دوزی و سوزن دوزی"),
    const UBusinessCategory(code: "59490002", nameEn: "Textiles & Spinning", nameFa: "نساجی و ریسندگی"),
    const UBusinessCategory(code: "59490003", nameEn: "Fabric Shop", nameFa: "پارچه فروشی"),
    const UBusinessCategory(code: "59490004", nameEn: "Yarn, Wool & Knitting Supplies Store", nameFa: "فروشگاه نخ، کاموا و لوازم بافندگی"),
    const UBusinessCategory(code: "59490005", nameEn: "Mattress, Blanket & Bedding", nameFa: "تشک، پتو و کالای خواب"),
    const UBusinessCategory(code: "59490006", nameEn: "Sack & Bag Sewing", nameFa: "گونی و کیسه دوزی"),
    const UBusinessCategory(code: "59490007", nameEn: "Dyeing", nameFa: "رنگرزی و صباغی"),
    const UBusinessCategory(code: "59490008", nameEn: "Haberdashery", nameFa: "خرازی"),
    const UBusinessCategory(code: "59490009", nameEn: "Wedding Sofreh & Bridal Dress Supplies", nameFa: "لوازم و تزئینات سفره عقد و لباس عروس"),
    const UBusinessCategory(code: "59500000", nameEn: "Crystal & Glassware Store - Other", nameFa: "فروشگاه کریستال و بلور سایر کسب"),
    const UBusinessCategory(code: "59500001", nameEn: "Gift Items & Luxury Goods", nameFa: "لوازم کادویی و کالای لوکس"),
    const UBusinessCategory(code: "59600000", nameEn: "Direct Marketing - Insurance Services - Other", nameFa: "بازاریابی مستقیم- خدمات بیمه سایر کسب"),
    const UBusinessCategory(code: "59620000", nameEn: "Direct Marketing - Travel Services - Other", nameFa: "بازاریابی مستقیم- خدمات مسافری سایر کسب"),
    const UBusinessCategory(code: "59630000", nameEn: "Door-to-door Advertising & Sales - Other", nameFa: "تبلیغات و فروش خانه به خانه سایر کسب"),
    const UBusinessCategory(code: "59640000", nameEn: "Direct Marketing - Catalog Mailing - Other", nameFa: "بازاریابی مستقیم- ارسال کاتالوگ سایر کسب"),
    const UBusinessCategory(code: "59650000", nameEn: "Direct Marketing - Catalog & Retail Mix - Other", nameFa: "بازاریابی مستقیم- ترکیب فروش کاتالوگی و خرد سایر کسب"),
    const UBusinessCategory(code: "59660000", nameEn: "Direct Marketing - Seller-initiated Contact - Other", nameFa: "بازاریابی مستقیم- فروش بر اساس تماس فروشنده با مشتری سایر کسب"),
    const UBusinessCategory(code: "59670000", nameEn: "Direct Marketing - Customer-initiated Contact - Other", nameFa: "بازاریابی مستقیم- فروش بر اساس تماس مشتری با فروشنده سایر کسب"),
    const UBusinessCategory(code: "59680000", nameEn: "Direct Marketing - Subscription - Other", nameFa: "بازاریابی مستقیم -فروش مستمر (اشتراک) سایر کسب"),
    const UBusinessCategory(code: "59690000", nameEn: "Direct Marketing - Other Methods", nameFa: "بازاریابی مستقیم- سایر روشها سایر کسب"),
    const UBusinessCategory(code: "59700000", nameEn: "Craft & Handicraft Supply Stores - Other", nameFa: "فروشگاههای تجهیزات ساخت کاردستی و صنایع دستی هنری سایر کسب"),
    const UBusinessCategory(code: "59700001", nameEn: "Handicrafts", nameFa: "صنایع دستی"),
    const UBusinessCategory(code: "59700002", nameEn: "Filigree Work", nameFa: "ملیله کاری"),
    const UBusinessCategory(code: "59700003", nameEn: "Pottery & Ceramics", nameFa: "کوزه و سفال گری"),
    const UBusinessCategory(code: "59710000", nameEn: "Art Dealers & Gallery Owners - Other", nameFa: "فروشندگان آثارهنری و صاحبان گالریها سایر کسب"),
    const UBusinessCategory(code: "59710001", nameEn: "Art Gallery", nameFa: "گالری هنری"),
    const UBusinessCategory(code: "59710002", nameEn: "Design, Graphics & Painting", nameFa: "طراحی و گرافیک و نقاشی"),
    const UBusinessCategory(code: "59710003", nameEn: "Calligraphy & Sign Writing", nameFa: "خطاطی و تابلو نویسی"),
    const UBusinessCategory(code: "59720000", nameEn: "Coin & Stamp Stores - Other", nameFa: "فروشگاههای سکه و تمبر سایر کسب"),
    const UBusinessCategory(code: "59730000", nameEn: "Religious Goods Stores - Other", nameFa: "فروشگاههای کالای مذهبی سایر کسب"),
    const UBusinessCategory(code: "59750000", nameEn: "Medical Hearing Aids - Other", nameFa: "لوازم کمک شنوایی پزشکی (سمعک) سایر کسب"),
    const UBusinessCategory(code: "59760000", nameEn: "Orthopedic & Prosthetic Supplies - Other", nameFa: "لوازم ارتوپدی پزشکی و اعضا مصنوعی سایر کسب"),
    const UBusinessCategory(code: "59770000", nameEn: "Cosmetics Store - Other", nameFa: "فروشگاه لوازم آرایشی سایر کسب"),
    const UBusinessCategory(code: "59770001", nameEn: "Cosmetics & Hygiene Products", nameFa: "لوازم آرایشی و بهداشتی"),
    const UBusinessCategory(code: "59770002", nameEn: "Perfume & Cologne", nameFa: "عطر و ادکلن"),
    const UBusinessCategory(code: "59780000", nameEn: "Printing Machines - Sales & Service - Other", nameFa: "ماشین چاپ- فروش و ارائه خدمات سایر کسب"),
    const UBusinessCategory(code: "59830000", nameEn: "Fuel Sellers - Other", nameFa: "فروشندگان سوخت سایر کسب"),
    const UBusinessCategory(code: "59920000", nameEn: "Florists - Other", nameFa: "گلفروشیها سایر کسب"),
    const UBusinessCategory(code: "59930000", nameEn: "Stores & Kiosks", nameFa: "فروشگاهها و دکه"),
    const UBusinessCategory(code: "59930001", nameEn: "Hookah & Accessories Store", nameFa: "فروشگاه قلیان و متعلقات"),
    const UBusinessCategory(code: "59940000", nameEn: "Newspapers", nameFa: "روزنامه"),
    const UBusinessCategory(code: "59950000", nameEn: "Pet Stores & Related Goods - Other", nameFa: "فروشگاه حیوانات خانگی و کالاهای مرتبط سایر کسب"),
    const UBusinessCategory(code: "59950001", nameEn: "Bird & Fish Store", nameFa: "فروشگاه پرنده و ماهی"),
    const UBusinessCategory(code: "59950002", nameEn: "Pet Store - Animals, Food & Supplies", nameFa: "فروشگاه حیوانات خانگی و غذا و لوازم آنها"),
    const UBusinessCategory(code: "59960000", nameEn: "Swimming Pools - Sales & Service - Other", nameFa: "استخرهای شنا -فروش و خدمات سایر کسب"),
    const UBusinessCategory(code: "59970000", nameEn: "Razor Sales & Service - Other", nameFa: "ریش تراش فروش و خدمات سایر کسب"),
    const UBusinessCategory(code: "59980000", nameEn: "Tent & Mosquito Net", nameFa: "خیمه و پشه"),
    const UBusinessCategory(code: "59990000", nameEn: "Misc & Special Retail - Other", nameFa: "خرده فروشی کالاهای متفرقه و خاص سایر کسب"),
    const UBusinessCategory(code: "60100000", nameEn: "Financial Institutions - Manual Payment - Other", nameFa: "موسسات مالی- عملیات پرداخت دستی سایر کسب"),
    const UBusinessCategory(code: "60110000", nameEn: "Financial Institutions - Automatic Payment - Other", nameFa: "موسسات مالی- عملیات پرداخت اتوماتیک سایر کسب"),
    const UBusinessCategory(code: "60120000", nameEn: "Financial Institutions - Goods & Services - Other", nameFa: "موسسات مالی- کالا و خدمات سایر کسب"),
    const UBusinessCategory(code: "60510000", nameEn: "Non-financial Institutions - Currency, Non-electronic Transfer, Traveler's Check, Savings - Other", nameFa: "موسسات غیر مالی ارز، حواله غیرالکتریکی، چک مسافرتی، پس انداز و صندوقهای سپرده گذاری سایر کسب"),
    const UBusinessCategory(code: "62110000", nameEn: "Brokerage - Other", nameFa: "دلالی سایر کسب"),
    const UBusinessCategory(code: "63000000", nameEn: "Insurance & Financial Contracts - Other", nameFa: "بیمه و قراردادهای مالی سایر کسب"),
    const UBusinessCategory(code: "65130000", nameEn: "Real Estate Management & Rental Agencies - Other", nameFa: "آژانسهای فروش مدیریت و اجاره املاک سایر کسب"),
    const UBusinessCategory(code: "70110000", nameEn: "Accommodation - Hotel, Inn & Lodging Services - Other", nameFa: "خدمات اقامتی هتل، مسافرخانه، اقامتگاه و مراکز خدمات اقامتی سایر کسب"),
    const UBusinessCategory(code: "70110001", nameEn: "Inn, Guesthouse & Pension", nameFa: "مسافرخانه و مهمانپذير و پانسیون"),
    const UBusinessCategory(code: "70110002", nameEn: "Hotel", nameFa: "هتل"),
    const UBusinessCategory(code: "70120000", nameEn: "Timeshare - Other", nameFa: "مالکیت مشترک سایر کسب"),
    const UBusinessCategory(code: "70320000", nameEn: "Sports & Recreation Camps - Other", nameFa: "اردوگاههای ورزشی تفریحی سایر کسب"),
    const UBusinessCategory(code: "70330000", nameEn: "Forest Recreation Parks - Other", nameFa: "پارکهای جنگلی تفریحی سایر کسب"),
    const UBusinessCategory(code: "72100000", nameEn: "Laundry", nameFa: "رختشوی خانه"),
    const UBusinessCategory(code: "72110000", nameEn: "Shop", nameFa: "مغازه"),
    const UBusinessCategory(code: "72160000", nameEn: "Dry Cleaning", nameFa: "خشک"),
    const UBusinessCategory(code: "72170000", nameEn: "Carpet Washing & Upholstery Cleaning - Other", nameFa: "قالی شویی و شستشوی روکش مبلمان سایر کسب"),
    const UBusinessCategory(code: "72210000", nameEn: "Photography Studios - Other", nameFa: "استودیوهای عکاسی سایر کسب"),
    const UBusinessCategory(code: "72300000", nameEn: "Beauty Salons & Barbershops - Other", nameFa: "سالنهای زیبایی و آرایشگاهها سایر کسب"),
    const UBusinessCategory(code: "72300001", nameEn: "Men's Barbering", nameFa: "آرایشگری مردانه"),
    const UBusinessCategory(code: "72300002", nameEn: "Women's Hairdressing & Beauty Salons", nameFa: "آرایشگری زنانه و سالنهای زیبایی"),
    const UBusinessCategory(code: "72510000", nameEn: "Shoe Repair, Cleaning & Polishing - Other", nameFa: "تعمیر، نظافت و واکس کفش و کلاه سایر کسب"),
    const UBusinessCategory(code: "72610000", nameEn: "Funeral & Burial Services - Other", nameFa: "خدمات کفن و دفن سایر کسب"),
    const UBusinessCategory(code: "72760000", nameEn: "Tax Payment Services - Other", nameFa: "خدمات پرداخت مالیات سایر کسب"),
    const UBusinessCategory(code: "72770000", nameEn: "Consulting Services - Loan, Marriage & Personal - Other", nameFa: "خدمات مشاوره- وام، ازدواج و شخصی سایر کسب"),
    const UBusinessCategory(code: "72770001", nameEn: "Marriage Counseling Services", nameFa: "خدمات مشاوره ازدواج"),
    const UBusinessCategory(code: "72780000", nameEn: "Buy & Sell Agencies - Other", nameFa: "بنگاههای خرید و فروش سایر کسب"),
    const UBusinessCategory(code: "72960000", nameEn: "Clothing Rental - Uniforms & Special Attire - Other", nameFa: "اجاره لباس- لباس فرم، یونیفرم و لباسهای خاص سایر کسب"),
    const UBusinessCategory(code: "72970000", nameEn: "Massage Parlors - Other", nameFa: "سالنهای ماساژ سایر کسب"),
    const UBusinessCategory(code: "72980000", nameEn: "Health & Beauty Centers - Other", nameFa: "مراکز سلامتی و زیبایی سایر کسب"),
    const UBusinessCategory(code: "72990000", nameEn: "Misc Personal Services [Other]", nameFa: "خدمات شخصی متفرقه [سایر موارد] سایر کسب"),
    const UBusinessCategory(code: "72990001", nameEn: "Event & Ceremony Services", nameFa: "خدمات مجالس و تشریفات"),
    const UBusinessCategory(code: "73110000", nameEn: "Advertising Services - Other", nameFa: "خدمات تبلیغاتی سایر کسب"),
    const UBusinessCategory(code: "73210000", nameEn: "Credit Card Reporting Agencies - Other", nameFa: "آژانسهای گزارش مصرف کارتهای اعتباری سایر کسب"),
    const UBusinessCategory(code: "73330000", nameEn: "Commercial Photography, Art & Graphics - Other", nameFa: "عکاسی، هنر و گرافیک تجاری سایر کسب"),
    const UBusinessCategory(code: "50390000", nameEn: "Construction Materials [Other]", nameFa: "مصالح ساختمانی [سایر موارد] سایر کسب"),
    const UBusinessCategory(code: "53310000", nameEn: "Grocery Store - Other", nameFa: "خواروبار فروشی سایر کسب"),
    const UBusinessCategory(code: "53990000", nameEn: "Misc General Goods - Other", nameFa: "کالاهای عمومی متفرقه سایر کسب"),
    const UBusinessCategory(code: "54110000", nameEn: "Supermarkets & Food Product Stores - Other", nameFa: "سوپرمارکتها و فروشگاههای محصولات غذایی سایر کسب"),
    const UBusinessCategory(code: "54110001", nameEn: "Supermarket & Grocery", nameFa: "سوپرمارکت و خواروبارفروشی"),
    const UBusinessCategory(code: "54110002", nameEn: "Consumer Cooperative", nameFa: "تعاونی مصرف"),
    const UBusinessCategory(code: "54110003", nameEn: "Detergent & Hygiene Products Distributors", nameFa: "توزیع کنندگان مواد شوینده و بهداشتی"),
    const UBusinessCategory(code: "54220000", nameEn: "Packaged Meat Sellers", nameFa: "فروشندگان گوشت بسته"),
    const UBusinessCategory(code: "54220001", nameEn: "Slaughterhouse", nameFa: "کشتارگاه"),
    const UBusinessCategory(code: "54220002", nameEn: "Butcher & Meat Products", nameFa: "قصابی و فروش محصولات گوشتی"),
    const UBusinessCategory(code: "54220004", nameEn: "Meat Products - Burger, Sausage & Cold Cuts", nameFa: "فرآورده های گوشتی، همبرگر، سوسیس و کالباس"),
    const UBusinessCategory(code: "54410000", nameEn: "Confectioneries & Nut Shops - Other", nameFa: "قنادیها و آجیل فروشیها سایر کسب"),
    const UBusinessCategory(code: "54410001", nameEn: "Confectionery & Pastry Shop", nameFa: "قنادی و شیرینی فروشی"),
    const UBusinessCategory(code: "54410002", nameEn: "Dried Fruit & Nut Seller", nameFa: "خشکبار و آجیل فروش"),
    const UBusinessCategory(code: "54410003", nameEn: "Halva Maker & Oil Presser", nameFa: "حلواساز و عصار"),
    const UBusinessCategory(code: "54410004", nameEn: "Honey Shop", nameFa: "عسل فروشی"),
    const UBusinessCategory(code: "54410005", nameEn: "Sohan & Gaz", nameFa: "سوهان و گز"),
    const UBusinessCategory(code: "54410006", nameEn: "Saffron Shop", nameFa: "زعفران فروشی"),
    const UBusinessCategory(code: "54510000", nameEn: "Dairy Product Stores - Other", nameFa: "فروشگاههای محصولات لبنی سایر کسب"),
    const UBusinessCategory(code: "54620000", nameEn: "Bakery", nameFa: "نانوایی"),
    const UBusinessCategory(code: "54620001", nameEn: "Bakery & Fancy Bread", nameFa: "نانوایی و نان فانتزی"),
    const UBusinessCategory(code: "54620002", nameEn: "Mill & Flour Shop", nameFa: "آسیاب و آرد فروشی"),
    const UBusinessCategory(code: "54990000", nameEn: "Misc Food Store - Mini Market (Grocery) - Other", nameFa: "فروشگاه مواد غذایی متفرقه- مینی مارکت (بقالی)- فروشگاه کالای خاص سایر کسب"),
    const UBusinessCategory(code: "54990001", nameEn: "Food Production & Distribution Company", nameFa: "شرکت تولید و پخش مواد غذایی"),
    const UBusinessCategory(code: "54990002", nameEn: "Grains & Legumes", nameFa: "غلات و حبوبات"),
    const UBusinessCategory(code: "54990003", nameEn: "Fruit & Vegetable Shop", nameFa: "میوه و سبزی فروشی"),
    const UBusinessCategory(code: "54990004", nameEn: "Fruit & Vegetable Market", nameFa: "میدان میوه و تره بار"),
    const UBusinessCategory(code: "54990005", nameEn: "Olive, Pickle & Spice Store", nameFa: "فروشگاه زیتون، ترشی و ادویه جات"),
    const UBusinessCategory(code: "54990006", nameEn: "Ice Shop", nameFa: "یخ فروشی"),
    const UBusinessCategory(code: "54990007", nameEn: "Tea, Coffee & Chocolate Shop", nameFa: "فروشگاه چای، قهوه و شکلات"),
    const UBusinessCategory(code: "55110000", nameEn: "Cars & Trucks (New & Used) - Sales, Service, Repair, Parts & Lease - Other", nameFa: "خودرو و کامیون ( نو و دست دوم)- فروش، سرویس، تعمیر، قطعات و رهن سایر کسب"),
    const UBusinessCategory(code: "55110001", nameEn: "Authorized Iran Khodro Dealership", nameFa: "نمایندگی مجاز ایران خودرو"),
    const UBusinessCategory(code: "55110002", nameEn: "Authorized Saipa Dealership", nameFa: "نمایندگی مجاز سایپا"),
    const UBusinessCategory(code: "55110003", nameEn: "Authorized Other Automakers Dealership", nameFa: "نمایندگی مجاز سایر خودروسازان"),
    const UBusinessCategory(code: "55110004", nameEn: "Car Showroom & Dealership", nameFa: "نمایشگاه و فروشگاه اتومبیل"),
    const UBusinessCategory(code: "55110005", nameEn: "Leasing Services", nameFa: "خدمات لیزینگ"),
    const UBusinessCategory(code: "55210000", nameEn: "Cars & Trucks (Used Only) - Sales, Service, Repair, Parts & Lease - Other", nameFa: "خودرو و کامیون ( فقط دست دوم)- فروش، سرویس، تعمیر، قطعات و رهن سایر کسب"),
    const UBusinessCategory(code: "55320000", nameEn: "Tire Shops - Other", nameFa: "لاستیک فروشیها سایر کسب"),
    const UBusinessCategory(code: "55330000", nameEn: "Auto Parts & Accessories - Other", nameFa: "قطعات و لوازم خودرو سایر کسب"),
    const UBusinessCategory(code: "55330001", nameEn: "Spare Parts Shop", nameFa: "لوازم یدکی فروشی"),
    const UBusinessCategory(code: "55330002", nameEn: "Car Decoration & Alarm Installation", nameFa: "تزیینات اتومبیل و نصب دزدگیر"),
    const UBusinessCategory(code: "55330003", nameEn: "Car Upholsterers & Seat Makers", nameFa: "تشکدوزان و صندلی سازان اتومبیل"),
    const UBusinessCategory(code: "55410000", nameEn: "Service Station - Other", nameFa: "ایستگاه خدماتی سایر کسب"),
    const UBusinessCategory(code: "55410001", nameEn: "Fuel & Product Filling Station", nameFa: "جایگاه عرضه سوخت و فرآورده"),
    const UBusinessCategory(code: "55410002", nameEn: "CNG Filling Station", nameFa: "جایگاه عرضه CNG"),
    const UBusinessCategory(code: "55420000", nameEn: "Automated Fuel Stations - Other", nameFa: "جایگاههای سوخت اتوماتیک سایر کسب"),
    const UBusinessCategory(code: "55510000", nameEn: "Boat Sellers - Other", nameFa: "فروشندگان قایق سایر کسب"),
    const UBusinessCategory(code: "55610000", nameEn: "Recreational, Utility & Residential Trailer Sellers - Other", nameFa: "فروشندگان تریلرهای تفریحی، تاسیساتی و اقامتی سایر کسب"),
    const UBusinessCategory(code: "55710000", nameEn: "Motorcycle Parts Sellers & Stores - Other", nameFa: "فروشندگان و فروشگاههای لوازم موتور سیکلت سایر کسب"),
    const UBusinessCategory(code: "55920000", nameEn: "Home Sellers", nameFa: "فروشندگان خانه"),
    const UBusinessCategory(code: "55980000", nameEn: "Snowmobile Sellers - Other", nameFa: "فروشندگان خودروهای برفی سایر کسب"),
    const UBusinessCategory(code: "55990000", nameEn: "Machinery", nameFa: "ماشین"),
    const UBusinessCategory(code: "55990001", nameEn: "Drilling Machinery", nameFa: "ماشین آلات حفاری"),
    const UBusinessCategory(code: "55990002", nameEn: "Road & Construction Machinery", nameFa: "ماشین آلات راه سازی و ساختمانی"),
    const UBusinessCategory(code: "55990003", nameEn: "Agricultural Machinery & Implements", nameFa: "ماشین آلات و ادوات کشاورزی"),
    const UBusinessCategory(code: "55990004", nameEn: "Industrial Machinery", nameFa: "ماشین آلات صنعتی"),
    const UBusinessCategory(code: "55990005", nameEn: "Printing & Binding Machinery", nameFa: "ماشین آلات چاپ و صحافی"),
    const UBusinessCategory(code: "55990006", nameEn: "Poultry Machinery", nameFa: "ماشین آلات مرغداری"),
    const UBusinessCategory(code: "55990007", nameEn: "Lathe Machinery", nameFa: "ماشین آلات تراشکاری"),
    const UBusinessCategory(code: "55990008", nameEn: "Weighbridge Operator", nameFa: "باسکول داری"),
    const UBusinessCategory(code: "55990009", nameEn: "Crane", nameFa: "جرثقیل"),
    const UBusinessCategory(code: "56110000", nameEn: "Men's & Boys' Apparel & Accessories Store - Other", nameFa: "فروشگاه پوشاک و پوشاک جانبی (اکسسوری) مردانه و پسرانه سایر کسب"),
    const UBusinessCategory(code: "56210000", nameEn: "Women's Ready-made Clothing Store - Other", nameFa: "فروشگاه لباسهای زنانه پیش دوخته سایر کسب"),
    const UBusinessCategory(code: "56310000", nameEn: "Special Apparel & Accessories Store - Other", nameFa: "فروشگاه پوشاک خاص و جانبی (اکسسوری) سایر کسب"),
    const UBusinessCategory(code: "56310001", nameEn: "Shawl & Scarf Shop", nameFa: "شال و روسری فروشی"),
    const UBusinessCategory(code: "56310002", nameEn: "Costume Jewelry (Accessory) Store", nameFa: "فروشگاه بدلیجات تزئینی (اکسسوری)"),
    const UBusinessCategory(code: "56410000", nameEn: "Infant & Children's Apparel Store - Other", nameFa: "فروشگاه پوشاک نوزاد و کودک سایر کسب"),
    const UBusinessCategory(code: "56410001", nameEn: "Infant & Children's Clothing", nameFa: "پوشاک نوزاد و کودک"),
    const UBusinessCategory(code: "56410002", nameEn: "Baby Supplies & Layette", nameFa: "لوازم نوزاد و سیسمونی"),
    const UBusinessCategory(code: "56510000", nameEn: "Family Apparel Store - Other", nameFa: "فروشگاه پوشاک خانواده سایر کسب"),
    const UBusinessCategory(code: "56550000", nameEn: "Sports & Equestrian Apparel Store - Other", nameFa: "فروشگاه پوشاک ورزشی و سوارکاری سایر کسب"),
    const UBusinessCategory(code: "56610000", nameEn: "Shoe Stores - Other", nameFa: "کفش فروشیها سایر کسب"),
    const UBusinessCategory(code: "56810000", nameEn: "Leather, Wool & Fur - Other", nameFa: "چرم، پشم و پوست سایر کسب"),
    const UBusinessCategory(code: "56910000", nameEn: "Adult Apparel - Other", nameFa: "پوشاک بزرگسالان سایر کسب"),
    const UBusinessCategory(code: "56970000", nameEn: "Tailoring, Sewing & Mending - Other", nameFa: "خیاطی، دوزندگی و رفوگری البسه سایر کسب"),
    const UBusinessCategory(code: "56970001", nameEn: "Tailoring & Clothing Repair", nameFa: "خیاطی و تعمیرات لباس"),
    const UBusinessCategory(code: "56970002", nameEn: "Custom & Formal Women's Manto, Trousers & Clothing", nameFa: "مانتو و شلوار و لباس زنانه سفارشی و مجلسی"),
    const UBusinessCategory(code: "56970003", nameEn: "Bridal Dress", nameFa: "لباس عروس"),
    const UBusinessCategory(code: "56970004", nameEn: "Safety Equipment & Workwear", nameFa: "لوازم ایمنی و لباس کار"),
    const UBusinessCategory(code: "56970005", nameEn: "Military Uniform Tailoring", nameFa: "دوزندگی لباس نظامی"),
    const UBusinessCategory(code: "56980000", nameEn: "Wig & Hairpiece Store - Other", nameFa: "فروشگاه موی مصنوعی و کلاه گیس سایر کسب"),
    const UBusinessCategory(code: "56990000", nameEn: "Misc Apparel & Accessories - Other", nameFa: "پوشاک و پوشاک جانبی متفرقه سایر کسب"),
    const UBusinessCategory(code: "56990002", nameEn: "Other Apparel Stores (Gloves, Hats, Scarves, Socks, Towels, etc.)", nameFa: "سایر فروشگاههای پوشاک (دستکش،کلاه،شال گردن، جوراب، حوله و ...)"),
    const UBusinessCategory(code: "56990003", nameEn: "Textiles & Knitwear", nameFa: "منسوجات و کالای کشباف"),
    const UBusinessCategory(code: "50130000", nameEn: "Auto Spare Parts - Other", nameFa: "لوازم یدکی اتومبیل سایر کسب"),
    const UBusinessCategory(code: "93990000", nameEn: "Other Government Services", nameFa: "سایر خدمات دولتی سایر کسب"),
    const UBusinessCategory(code: "93990001", nameEn: "Notary Public Offices", nameFa: "دفاتر ثبت اسناد رسمی"),
    const UBusinessCategory(code: "93990002", nameEn: "Government Service Counter Offices (Pishkhan)", nameFa: "دفاتر پیشخوان دولت"),
    const UBusinessCategory(code: "93990003", nameEn: "Embassy", nameFa: "سفارتخانه"),
    const UBusinessCategory(code: "93990004", nameEn: "Police +10 Offices", nameFa: "دفاتر پلیس + 10"),
    const UBusinessCategory(code: "93990005", nameEn: "Rural ICT Offices", nameFa: "دفاتر ICT روستایی"),
    const UBusinessCategory(code: "93990006", nameEn: "Municipality", nameFa: "شهرداری"),
    const UBusinessCategory(code: "93990007", nameEn: "Subscriber Affairs Offices", nameFa: "دفاتر امور مشترکین"),
    const UBusinessCategory(code: "93990009", nameEn: "Government Punishment Organization (Tazirat)", nameFa: "سازمان تعزیرات حکومتی"),
    const UBusinessCategory(code: "93990010", nameEn: "Civil Registration Organization", nameFa: "سازمان ثبت احوال"),
    const UBusinessCategory(code: "93990011", nameEn: "License Plate Replacement Center", nameFa: "مرکز تعویض پلاک"),
    const UBusinessCategory(code: "93990012", nameEn: "Forensic Medicine Organization", nameFa: "سازمان پزشکی قانونی"),
    const UBusinessCategory(code: "93990013", nameEn: "Fire Department", nameFa: "سازمان آتش نشانی"),
    const UBusinessCategory(code: "93990014", nameEn: "Vehicle Technical Inspection Center", nameFa: "مرکز معاینه فنی خودرو"),
    const UBusinessCategory(code: "93990015", nameEn: "City Electronic Services Offices", nameFa: "دفاتر خدمات الکترونیک شهر"),
    const UBusinessCategory(code: "94020000", nameEn: "Postal Services - Government Only - Other", nameFa: "خدمات پستی -مخصوص دولت سایر کسب"),
    const UBusinessCategory(code: "73380000", nameEn: "Duplication, Copying & Restoration Services - Other", nameFa: "خدمات تکثیر، کپی و بازسازی سایر کسب"),
    const UBusinessCategory(code: "73380001", nameEn: "Stamp, Logo & Screen Printing", nameFa: "مهر و آرم و چاپ اسکرین"),
    const UBusinessCategory(code: "73380002", nameEn: "Bookbinding, Notebook & Album Making", nameFa: "صحافی، دفتر و آلبوم سازی"),
    const UBusinessCategory(code: "73390000", nameEn: "Petition Writing - Other", nameFa: "عریضه نویسی سایر کسب"),
    const UBusinessCategory(code: "73420000", nameEn: "Pest Control & Extermination Services - Other", nameFa: "خدمات سمپاشی و دفع حشرات موذی سایر کسب"),
    const UBusinessCategory(code: "73490000", nameEn: "Cleaning Services - Other", nameFa: "خدمات نظافتی سایر کسب"),
    const UBusinessCategory(code: "73610000", nameEn: "Employment & Temp Staffing Agencies - Other", nameFa: "آژانسهای کاریابی و تامین نیروی کار موقت سایر کسب"),
    const UBusinessCategory(code: "73720000", nameEn: "Computer Programmers, Data Analysts & Custom System Designers - Other", nameFa: "برنامه نویسان کامپیوتری، تحلیلگران اطلاعات و طراحان سیستمهای کامپیوتری خاص سایر کسب"),
    const UBusinessCategory(code: "73750000", nameEn: "Data Recovery - Other", nameFa: "بازیابی اطلاعات سایر کسب"),
    const UBusinessCategory(code: "73790000", nameEn: "Computer Repair & Maintenance Services - Other", nameFa: "خدمات تعمیر و نگهداری کامپیوتر سایر کسب"),
    const UBusinessCategory(code: "73920000", nameEn: "Management, Consulting & Public Services - Other", nameFa: "مدیریت، مشاوره و خدمات مردمی سایر کسب"),
    const UBusinessCategory(code: "73930000", nameEn: "Security Systems, Private Guards, Armored Cars & Guard Dogs - Other", nameFa: "تامین کنندگان سیستمهای امنیتی، محافظ خصوصی، ماشینهای ضدگلوله و سگهای نگهبان سایر کسب"),
    const UBusinessCategory(code: "73930001", nameEn: "Camera Installers", nameFa: "نصابان دوربین"),
    const UBusinessCategory(code: "73940000", nameEn: "Equipment, Tool, Furniture & Device Rental - Other", nameFa: "رهن، اجاره تجهیزات،ابزار، مبلمان و دستگاههای مختلف سایر کسب"),
    const UBusinessCategory(code: "73940001", nameEn: "Event Rental Supplies", nameFa: "لوازم کرایه برگزاری مجالس"),
    const UBusinessCategory(code: "73950000", nameEn: "Photo Developing & Retouching Labs - Other", nameFa: "لابراتوارهای ظهور و رتوش عکس سایر کسب"),
    const UBusinessCategory(code: "73990000", nameEn: "Business Services [Other]", nameFa: "خدمات کسب وکار [سایر موارد] سایر کسب"),
    const UBusinessCategory(code: "73990001", nameEn: "Seminar & Conference Organizing", nameFa: "برگزاری سمینار و همایش"),
    const UBusinessCategory(code: "73990002", nameEn: "Official Translation Office", nameFa: "دارالترجمه رسمی"),
    const UBusinessCategory(code: "75120000", nameEn: "Car Rental Firms - Other", nameFa: "موسسات کرایه اتومبیل سایر کسب"),
    const UBusinessCategory(code: "75130000", nameEn: "Truck & Utility Trailer Rental Firms - Other", nameFa: "موسسات اجاره کامیون و تریلر تاسیساتی سایر کسب"),
    const UBusinessCategory(code: "75190000", nameEn: "Recreational Vehicle & Home Rental Firms", nameFa: "موسسات اجاره خودروهای تفریحاتی و خانه"),
    const UBusinessCategory(code: "75230000", nameEn: "Parking, Meters & Garages - Other", nameFa: "پارکینگ، پارکومتر و گاراژ سایر کسب"),
    const UBusinessCategory(code: "75310000", nameEn: "Auto Body Repair - Other", nameFa: "صافکاری خودرو سایر کسب"),
    const UBusinessCategory(code: "75340000", nameEn: "Tire Repair & Retreading Services - Other", nameFa: "خدمات تعمیر و روکش لاستیک خودرو سایر کسب"),
    const UBusinessCategory(code: "75350000", nameEn: "Car Painting - Other", nameFa: "نقاشی خودرو سایر کسب"),
    const UBusinessCategory(code: "75380000", nameEn: "Auto Services [Not Sellers] - Other", nameFa: "خدمات خودرو [ و نه فروشندگان] سایر کسب"),
    const UBusinessCategory(code: "75380001", nameEn: "Exhaust Making", nameFa: "اگزوزسازی"),
    const UBusinessCategory(code: "75380002", nameEn: "Vehicle Ironwork", nameFa: "آهن گری و آهن کشی انواع خودرو"),
    const UBusinessCategory(code: "75380003", nameEn: "Battery Maker & Seller", nameFa: "باطری ساز و باطری فروش"),
    const UBusinessCategory(code: "75380004", nameEn: "Auto Mechanics", nameFa: "تعمیرکاران خودرو"),
    const UBusinessCategory(code: "75380005", nameEn: "Auto Electrical Services", nameFa: "خدمات برق اتومبیل"),
    const UBusinessCategory(code: "75420000", nameEn: "Car Wash - Other", nameFa: "کارواش سایر کسب"),
    const UBusinessCategory(code: "75490000", nameEn: "Towing", nameFa: "یدک"),
    const UBusinessCategory(code: "76220000", nameEn: "Electronics Repair Shop - Other", nameFa: "تعمیرگاه لوازم الکترونیکی سایر کسب"),
    const UBusinessCategory(code: "76220001", nameEn: "Audio & Video Equipment Repair", nameFa: "تعمیرکار لوازم صوتی و تصویری"),
    const UBusinessCategory(code: "76230000", nameEn: "Refrigeration & Fridge-Freezer Repair Shop - Other", nameFa: "تعمیرگاه سیستمهای برودتی و یخچال فریزر سایر کسب"),
    const UBusinessCategory(code: "76290000", nameEn: "Small Electronic Devices Repair Shop - Other", nameFa: "تعمیرگاه لوازم و دستگاههای کوچک الکترونیکی سایر کسب"),
    const UBusinessCategory(code: "76290001", nameEn: "Home Appliance Repair", nameFa: "تعمیرکار لوازم خانگی"),
    const UBusinessCategory(code: "76310000", nameEn: "Watch, Clock & Jewelry Repair Shop - Other", nameFa: "تعمیرگاه ساعت مچی، ساعت دیواری و جواهرآلات سایر کسب"),
    const UBusinessCategory(code: "76410000", nameEn: "Furniture Repair, Restoration & Reupholstery - Other", nameFa: "تعمیر، بازسازی و تعویض روکش مبلمان سایر کسب"),
    const UBusinessCategory(code: "76920000", nameEn: "Welding Services - Other", nameFa: "خدمات جوشکاری سایر کسب"),
    const UBusinessCategory(code: "76990000", nameEn: "Misc Repair Shop & Related Services - Other", nameFa: "تعمیرگاه لوازم متفرقه و خدمات مرتبط سایر کسب"),
    const UBusinessCategory(code: "78290000", nameEn: "Multimedia Production & Distribution", nameFa: "پخش و تولید محصولات چند رسانه"),
    const UBusinessCategory(code: "78320000", nameEn: "Cinema - Other", nameFa: "سینما سایر کسب"),
    const UBusinessCategory(code: "78410000", nameEn: "Film & DVD Rental Stores - Other", nameFa: "فروشگاههای کرایه فیلم و DVD سایر کسب"),
    const UBusinessCategory(code: "79220000", nameEn: "Theater Producers & Ticket Agencies - Other", nameFa: "تهیه کنندگان تئاتر و آژانسهای فروش بلیط تئاتر سایر کسب"),
    const UBusinessCategory(code: "79290000", nameEn: "Bands, Orchestras & Misc Entertainment - Other", nameFa: "گروههای موسیقی، ارکستر و سرگرمیهای متفرقه سایر کسب"),
    const UBusinessCategory(code: "79320000", nameEn: "Billiard Halls - Other", nameFa: "سالنهای بیلیارد سایر کسب"),
    const UBusinessCategory(code: "79330000", nameEn: "Bowling Alleys - Other", nameFa: "سالنهای بولینگ سایر کسب"),
    const UBusinessCategory(code: "79410000", nameEn: "Commercial Sports, Pro Associations, Fields & Event Organizers - Other", nameFa: "ورزشهای تجاری، انجمنهای ورزش حرفه ای، زمینهای ورزشی، برگزارکنندگان مسابقات سایر کسب"),
    const UBusinessCategory(code: "79410001", nameEn: "Sports Stadiums", nameFa: "استادیومهای ورزشی"),
    const UBusinessCategory(code: "79910000", nameEn: "Exhibitions & Tourist Attractions - Other", nameFa: "نمایشگاهها و جاذبه های توریستی سایر کسب"),
    const UBusinessCategory(code: "79910001", nameEn: "Museum", nameFa: "موزه"),
    const UBusinessCategory(code: "79920000", nameEn: "Public Golf Class Organizers - Other", nameFa: "برگزارکنندگان کلاسهای عمومی گلف سایر کسب"),
    const UBusinessCategory(code: "79930000", nameEn: "Video Game & Amusement Machine Sellers - Other", nameFa: "فروشندگان دستگاه های بازی ویدئویی و سرگرمی سایر کسب"),
    const UBusinessCategory(code: "79940000", nameEn: "Video Game & Amusement Arcades - Other", nameFa: "سالنهای دستگاههای بازی ویدئویی و سرگرمی سایر کسب"),
    const UBusinessCategory(code: "79960000", nameEn: "Amusement Park, Circus & Carnival - Other", nameFa: "شهربازی، سیرک و کارناوال سایر کسب"),
    const UBusinessCategory(code: "79970000", nameEn: "Private Clubs, Golf & Equestrian Clubs - Other", nameFa: "باشگاههای خصوصی، باشگا ههای خصوصی آموزش گلف و سوارکاری سایر کسب"),
    const UBusinessCategory(code: "79980000", nameEn: "Public Aquarium, Zoo & Dolphin Show Pools - Other", nameFa: "آکواریوم عمومی، باغ وحش و استخرهای نمایش دلفینها سایر کسب"),
    const UBusinessCategory(code: "79980001", nameEn: "Aquarium & Dolphinarium", nameFa: "آکواریوم و دلفیناریوم"),
    const UBusinessCategory(code: "79990000", nameEn: "Recreational Services [Other]", nameFa: "خدمات تفریحی [سایر موارد] سایر کسب"),
    const UBusinessCategory(code: "79990001", nameEn: "Water Park", nameFa: "پارک آبی"),
    const UBusinessCategory(code: "80110000", nameEn: "Physicians [Other]", nameFa: "پزشکان [سایر موارد] سایر کسب"),
    const UBusinessCategory(code: "80110001", nameEn: "General Practitioner", nameFa: "پزشک عمومی"),
    const UBusinessCategory(code: "80110002", nameEn: "Specialist Physician", nameFa: "پزشک متخصص"),
    const UBusinessCategory(code: "80210000", nameEn: "Dental & Orthopedic Services - Other", nameFa: "خدمات دندانپزشکی و ارتوپدی سایر کسب"),
    const UBusinessCategory(code: "80310000", nameEn: "Bone Disease Specialists - Other", nameFa: "متخصصان بیماری استخوان سایر کسب"),
    const UBusinessCategory(code: "80420000", nameEn: "Ophthalmologists & Optometrists - Other", nameFa: "چشم پزشکان و بینایی سنجها سایر کسب"),
    const UBusinessCategory(code: "80430000", nameEn: "Eyeglasses & Lens Services - Other", nameFa: "خدمات عینک و لنز سایر کسب"),
    const UBusinessCategory(code: "80490000", nameEn: "Podiatrists - Other", nameFa: "پزشکان متخصص پا سایر کسب"),
    const UBusinessCategory(code: "80500000", nameEn: "Nursing & Personal Care Centers - Other", nameFa: "مراکز پرستاری و مراقبتهای فردی سایر کسب"),
    const UBusinessCategory(code: "80500001", nameEn: "Nursing Home", nameFa: "خانه سالمندان"),
    const UBusinessCategory(code: "80620000", nameEn: "Hospitals - Other", nameFa: "بیمارستانها سایر کسب"),
    const UBusinessCategory(code: "80620001", nameEn: "Government Hospital", nameFa: "بیمارستان دولتی"),
    const UBusinessCategory(code: "80620002", nameEn: "Private Hospital", nameFa: "بیمارستان خصوصی"),
    const UBusinessCategory(code: "80620003", nameEn: "Clinic", nameFa: "درمانگاه"),
    const UBusinessCategory(code: "80710000", nameEn: "Medical & Dental Laboratories - Other", nameFa: "لابراتورهای پزشکی و دندانپزشکی سایر کسب"),
    const UBusinessCategory(code: "80990000", nameEn: "Medical Services & Health Specialists [Other]", nameFa: "خدمات درمانی و متخصصان سلامت (سایر موارد) سایر کسب"),
    const UBusinessCategory(code: "80990001", nameEn: "Radiology & Ultrasound Services", nameFa: "خدمات رادیولوژی و سونوگرافی"),
    const UBusinessCategory(code: "80990002", nameEn: "Addiction Treatment Clinic", nameFa: "کلینیک ترک اعتیاد"),
    const UBusinessCategory(code: "80990003", nameEn: "Laser & Beauty", nameFa: "لیزر و زیبایی"),
    const UBusinessCategory(code: "80990004", nameEn: "Herbalist & Medicinal Plants", nameFa: "عطاری و گیاهان دارویی"),
    const UBusinessCategory(code: "80990005", nameEn: "Skin & Hair Clinic", nameFa: "کلینیک پوست و مو"),
    const UBusinessCategory(code: "80990006", nameEn: "Blood Transfusion Organization", nameFa: "سازمان انتقال خون"),
    const UBusinessCategory(code: "80990007", nameEn: "Psychology & Speech Therapy Clinics", nameFa: "کلینیکهای روانشناسی و گفتاردرمانی"),
    const UBusinessCategory(code: "81110000", nameEn: "Legal & Judicial Services - Other", nameFa: "خدمات حقوقی و دادگستری سایر کسب"),
    const UBusinessCategory(code: "81110001", nameEn: "Marriage & Divorce Offices", nameFa: "دفاتر ازدواج و طلاق"),
    const UBusinessCategory(code: "82110000", nameEn: "Primary, Middle & High Schools - Other", nameFa: "مدارس ابتدایی، راهنمایی و دبیرستان سایر کسب"),
    const UBusinessCategory(code: "82110001", nameEn: "Primary Schools", nameFa: "مدارس ابتدایی"),
    const UBusinessCategory(code: "82110002", nameEn: "Middle Schools", nameFa: "مدارس راهنمایی"),
    const UBusinessCategory(code: "82110003", nameEn: "Secondary Schools", nameFa: "مدارس متوسطه"),
    const UBusinessCategory(code: "82110004", nameEn: "Vocational Schools (Honarestan)", nameFa: "هنرستانها"),
    const UBusinessCategory(code: "82110005", nameEn: "Daneshvar Schools", nameFa: "مدارس دانش"),
    const UBusinessCategory(code: "82200000", nameEn: "Colleges & Universities", nameFa: "کالجها، دانشگاه"),
    const UBusinessCategory(code: "82200001", nameEn: "Public University", nameFa: "دانشگاه دولتی"),
    const UBusinessCategory(code: "82200002", nameEn: "Azad University", nameFa: "دانشگاه آزاد"),
    const UBusinessCategory(code: "82200003", nameEn: "Non-profit University", nameFa: "دانشگاه غیرانتفاعی"),
    const UBusinessCategory(code: "82200004", nameEn: "University of Applied Science & Technology", nameFa: "دانشگاه جامع علمی کاربردی"),
    const UBusinessCategory(code: "82200005", nameEn: "Payam-e Noor University", nameFa: "دانشگاه پیام نور"),
    const UBusinessCategory(code: "82200006", nameEn: "University of Medical Sciences", nameFa: "دانشگاه علوم پزشکی"),
    const UBusinessCategory(code: "82200007", nameEn: "Teacher Training Center", nameFa: "مرکز تربیت معلم"),
    const UBusinessCategory(code: "82410000", nameEn: "Correspondence Education Centers", nameFa: "مراکز آموزش مکاتیه"),
    const UBusinessCategory(code: "82440000", nameEn: "Business Training Centers", nameFa: "مراکز آموزش کسب"),
    const UBusinessCategory(code: "82490000", nameEn: "Technical & Vocational Schools - Other", nameFa: "آموزشگاههای فنی و حرفه ای سایر کسب"),
    const UBusinessCategory(code: "82490001", nameEn: "Sewing & Pattern Design School", nameFa: "آموزشگاه خیاطی و طراحی دوخت"),
    const UBusinessCategory(code: "82490002", nameEn: "Hairdressing & Barbering School", nameFa: "آموزشگاه آرایشگری و پیرایشگری"),
    const UBusinessCategory(code: "82490003", nameEn: "Computer School (Hardware & Software)", nameFa: "آموزشگاه کامپیوتر (سخت افزار- نرم"),
    const UBusinessCategory(code: "82490004", nameEn: "Robotics School", nameFa: "آموزشگاه رباتیک"),
    const UBusinessCategory(code: "82490005", nameEn: "Mobile Repair School", nameFa: "آموزشگاه تعمیرات موبایل"),
    const UBusinessCategory(code: "82490006", nameEn: "Flight School", nameFa: "آموزشگاه خلبانی"),
    const UBusinessCategory(code: "82490007", nameEn: "Electrical School", nameFa: "آموزشگاه برق"),
    const UBusinessCategory(code: "82490008", nameEn: "Carpet & Weaving School", nameFa: "آموزشگاه فرش، قالیبافی و تابلو فرش"),
    const UBusinessCategory(code: "82990000", nameEn: "Other Educational Service Providers", nameFa: "سایر مراکز ارائه دهنده خدمات آموزشی سایر کسب"),
    const UBusinessCategory(code: "82990001", nameEn: "Foreign Language School", nameFa: "آموزشگاه زبانهای خارجی"),
    const UBusinessCategory(code: "82990002", nameEn: "Art & Music School", nameFa: "آموزشگاه هنر و موسیقی"),
    const UBusinessCategory(code: "82990003", nameEn: "Driving School", nameFa: "آموزشگاه رانندگی"),
    const UBusinessCategory(code: "82990004", nameEn: "Tutoring & Exam Prep School", nameFa: "آموزشگاه درسی و کنکور"),
    const UBusinessCategory(code: "82990005", nameEn: "Large & Multi-purpose Schools", nameFa: "آموزشگاههای بزرگ و چند منظوره"),
    const UBusinessCategory(code: "83510000", nameEn: "Childcare Services - Other", nameFa: "خدمات نگهداری از کودکان سایر کسب"),
    const UBusinessCategory(code: "83510001", nameEn: "Kindergarten", nameFa: "مهد کودک"),
    const UBusinessCategory(code: "83980000", nameEn: "Charities & Social Services - Other", nameFa: "موسسات خیریه و خدمات اجتماعی سایر کسب"),
    const UBusinessCategory(code: "83980001", nameEn: "Imam Khomeini Relief Committee", nameFa: "کمیته امداد"),
    const UBusinessCategory(code: "8410000", nameEn: "Chiropractors - Other", nameFa: "کایروپراکتورها سایر کسب"),
    const UBusinessCategory(code: "86410000", nameEn: "Associations & Unions", nameFa: "انجمنها و اتحادیه"),
    const UBusinessCategory(code: "86510000", nameEn: "Political Organizations - Other", nameFa: "سازمانهای سیاسی سایر کسب"),
    const UBusinessCategory(code: "86610000", nameEn: "Religious Organizations - Other", nameFa: "سازمانهای مذهبی سایر کسب"),
    const UBusinessCategory(code: "86610001", nameEn: "Husseiniyeh, Mosques & Mosalla", nameFa: "حسینیه، مساجد و مصلی"),
    const UBusinessCategory(code: "86610002", nameEn: "Friday Imam & Marja Offices", nameFa: "دفاتر امام جمعه و مراجع"),
    const UBusinessCategory(code: "86610003", nameEn: "Seminary & Religious Schools", nameFa: "حوزه علمیه و مدارس دینی"),
    const UBusinessCategory(code: "86750000", nameEn: "Automobile Unions - Other", nameFa: "اتحادیه های خودرو سایر کسب"),
    const UBusinessCategory(code: "86990000", nameEn: "Other Membership Organizations - Other", nameFa: "سایر سازمانهای عضویت پذیر سایر کسب"),
    const UBusinessCategory(code: "87340000", nameEn: "Testing Labs (Non-medical) - Other", nameFa: "لابراتوارهای تست (غیرپزشکی) سایر کسب"),
    const UBusinessCategory(code: "89110000", nameEn: "Architecture, Engineering & Research Services - Other", nameFa: "خدمات معماری، مهندسی و پژوهشی سایر کسب"),
    const UBusinessCategory(code: "89110001", nameEn: "Architecture, Engineering & Surveying Services", nameFa: "خدمات معماری،مهندسی و نقشه برداری"),
    const UBusinessCategory(code: "89110002", nameEn: "Engineering & Drafting Supplies", nameFa: "لوازم مهندسی و نقشه کشی"),
    const UBusinessCategory(code: "89310000", nameEn: "Accounting, Auditing & Bookkeeping Services - Other", nameFa: "خدمات حسابداری، حسابرسی و دفترداری سایر کسب"),
    const UBusinessCategory(code: "89990000", nameEn: "Other Professional Services", nameFa: "سایر خدمات حرفه ای سایر کسب"),
    const UBusinessCategory(code: "89990001", nameEn: "Import & Export Trade Services", nameFa: "خدمات بازرگانی واردات و صادرات"),
    const UBusinessCategory(code: "89990002", nameEn: "Engineering Services, Engineering System", nameFa: "خدمات مهندسی، نظام مهندسی"),
    const UBusinessCategory(code: "89990003", nameEn: "Bathhouse Operators", nameFa: "گرمابه داران"),
    const UBusinessCategory(code: "89990004", nameEn: "Real Estate Agents", nameFa: "مشاورین املاک و مستغلات"),
    const UBusinessCategory(code: "89990005", nameEn: "Deep & Semi-deep Well Drilling", nameFa: "حفرچاه عمیق و نیمه عمیق"),
    const UBusinessCategory(code: "89990006", nameEn: "Immigration & Visa Services", nameFa: "خدمات مهاجرت و ویزا"),
    const UBusinessCategory(code: "92110000", nameEn: "Court & Judicial Services - Other", nameFa: "دادگاه و خدمات دادرسی سایر کسب"),
    const UBusinessCategory(code: "92110001", nameEn: "Dispute Resolution Council", nameFa: "شورای حل اختلاف"),
    const UBusinessCategory(code: "92220000", nameEn: "Fines - Other", nameFa: "جرایم سایر کسب"),
    const UBusinessCategory(code: "92230000", nameEn: "Bonds & Collateral Payment - Other", nameFa: "پرداخت اوراق قرضه و وثیقه سایر کسب"),
    const UBusinessCategory(code: "93110000", nameEn: "Tax Payment - Other", nameFa: "پرداخت مالیات سایر کسب"),
    const UBusinessCategory(code: "93110001", nameEn: "Customs Offices", nameFa: "ادارات گمرک"),
    const UBusinessCategory(code: "93110002", nameEn: "Tax Affairs Organization", nameFa: "سازمان امور مالیاتی"),
  ];
}
